### ISSUE TITLE
[UX] Need a message to inform user for importing calendar

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#100]
# Actual Result

When importing a calendar, it displays only the message "Request submitted". Sometimes the user has to wait quite a long time for the import process to be finished. While waiting, he/she doesn't know if the function is working or not until he receives a report email that tells him/her the import process has finished.

![Peek 2020-09-11 17-06](https://user-images.githubusercontent.com/69950655/92909904-c736b100-f451-11ea-9479-60d7a7a75c7a.gif)

# Expected Result

The "Request submitted" message should be changed to something to inform the user that he/she will receive a report email when the calendar finishes being imported.

**Comment by asmaNode** [comment]
@tlle14 investigating in this bug , i did not reproduce your scenario ,
importing new ics file trigger a notification message inform you ' Submitting importing calendar request' , this action work in asynchrone way so after finishing the importing request , the success notification  message is shown ,
my question is ,  the problem is after importing the calendar and when you reload there is a delay to display all the events ?

**Comment by MichaelBailly** [comment]
I guess the easy fix is to tell the user that he/she will receive an email at the end of the import process.

**Comment by tlle14** [comment]
> @tlle14 investigating in this bug , i did not reproduce your scenario ,
> importing new ics file trigger a notification message inform you ' Submitting importing calendar request' , this action work in asynchrone way so after finishing the importing request , the success notification message is shown ,
> my question is , the problem is after importing the calendar and when you reload there is a delay to display all the events ?

Hi @asmaNode : yes, sometimes it takes time to import the calendar and delay to display the events. 
I agree with Michael to tell user that he will receive the email when importing task is finished.

**Comment by asmaNode** [comment]
@MichaelBailly  @tlle14  it is ok ?
![bugfix2](https://user-images.githubusercontent.com/43316837/93869428-b0028980-fcc3-11ea-8544-ba4b368ec610.gif)

**Comment by tlle14** [comment]
Thank @asmaNode 
I will retest when you merge the code.

**Comment by hantt12** [comment]
The linebreak is not good though 
![20200930_2](https://user-images.githubusercontent.com/53081477/94667130-97841600-0338-11eb-8382-2b30bcd239a6.png)

**Comment by huy-ta** [comment]
> The linebreak is not good though
> ![20200930_2](https://user-images.githubusercontent.com/53081477/94667130-97841600-0338-11eb-8382-2b30bcd239a6.png)

We will create an issue to resolve this for all notifications. _issue to be created here_

**Comment by asmaNode** [comment]
## Definition of Done

#### What I have done

I have added a message to inform user that he will receive an email when the importing was completed

#### Environments tested

- Browser: Chrome (Ubuntu)
- Mode: Local & Dev (https://dev.open-paas.org)
