### ISSUE TITLE
Wrong behavior when invite users who has duplicated default calendar "My Calendar"

### ISSUE THREAD

**Issue by tuanlc** [OpenPaaS-Suite/esn-frontend-calendar#108]
### Context and reproduced steps
- During the migration from OBM to OpenPaaS, by somehow, user B has 2 "My calendar"
- user A login to calendar spa
- user A creates a new event with attendees: B & C

### Current behavior
- The created event does not appear on the organizer (user A) calendar
- The created event appears on the user C calendar

### Expected behavior
- The created event  must appear on the organizer (user A) calendar

### Additional info:  log on user A browser 
![Screenshot from 2020-09-18 15-05-35](https://user-images.githubusercontent.com/7950991/93576534-30c03d80-f9c5-11ea-927a-c66886362b0a.png)

**Comment by vincent-zurczak** [comment]
Hi,

I have just encountered this issue, although I have no idea whether other attendees have already logged in or not. The event does not appear in my calendar. Is it lost? Or is it just a problem of display?

Said differently, will I have to recreate it?

**Comment by tuanlc** [comment]
Hi @vincent-zurczak 

I'm checking the codebase. I keep you posted.

**Comment by tuanlc** [comment]
@vincent-zurczak can you provide the list of your attendees?

I have found that the bug appears when users already logged in. But not all users. I need to have more info from attendees

**Comment by vincent-zurczak** [comment]
I send you the list through a private message.

**Comment by tuanlc** [comment]
Thank @vincent-zurczak 

In your list of attendees contains an email that caused the same bug with @hoangdat 

I'm contacting the attendee to have more information.

**Comment by tuanlc** [comment]
**Update:**
After checking the log from the attendee, I have found that, he has 2 `default` calendar `My calendar`.
This also leads the issue that calendar app is break for the attendee.

I remove the duplicate and I success to invite him to an event.
@vincent-zurczak & @hoangdat can you re-try to create the events that you was failed?

**Comment by tuanlc** [comment]
**Update**: The special attendee confirmed that calendar app works for him

**Comment by tuanlc** [comment]
Duplicated `My Calendar` issue: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/116 that breaks users calendar app

**Comment by tuanlc** [comment]
### DoD

The bug was fixed by remove duplicated calendars. Preventing the duplicate calendars will be handled in issue https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/116
