### ISSUE TITLE
The title of the invitation email is not translated

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#111]
#### Steps to reproduce

- As **User B**:

  1. Login and go to Control Center.
  2. Change your language to something else other than English (let's say Vietnamese - Tiếng Việt).

- As **User A**:

  1. Login and go to the Calendar SPA
  2. Create a new event and add **User B** as an attendee. The title of the event is "Event1"

- As **User B**:

  1. Go to the Inbox SPA
  2. Go to the INBOX folder

##### Current behaviour

The title of the invitation email is not translated to **User B**'s selected language. It always uses English.

> New event from User B: Event1

##### Expected behaviour

The title of the invitation email should be translated to **User B**'s selected language. For example, in Vietnamese:

> Sự kiện mới từ User B: Event1

**Comment by asmaNode** [comment]
@huy-ta  how we can  translate a dynamic value :/ , if you have any idea tell me

**Comment by huy-ta** [comment]
@asmaNode Sorry my bad. It's not the whole title of the event that needs to be translated. For example:

> New event from John0 Doe0: user0 invited admin

should be translated to (in Vietnamese):

> Sự kiện mới từ John0 Doe0: user0 invited admin

The event's title, "user0 invited admin", doesn't need to and must not be translated.
