### ISSUE TITLE
Event time in email is always shown in UTC time

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#112]
Please refer to https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/issues/1770.

**Comment by huy-ta** [comment]
## Definition of Done

#### What I have done

I have fixed the issue via https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/674 and https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1309.

Here are the results:

 - When the user uses Vietnamese, Asia/Ho_Chi_Minh timezone, and 24-hour time format:

  ![demo_1](https://user-images.githubusercontent.com/24670327/94654558-6bac6480-0327-11eb-866e-52627003216d.png)

  - When the user uses Vietnamese, Asia/Ho_Chi_Minh timezone, and 12-hour time format:

  ![demo_2](https://user-images.githubusercontent.com/24670327/94654566-6cdd9180-0327-11eb-8f94-5a278c40eea6.png)

  - When the user uses Chinese, Asia/Ho_Chi_Minh timezone, and 12-hour time format:

  ![demo_3](https://user-images.githubusercontent.com/24670327/94654574-70711880-0327-11eb-86da-d21b7e351b8e.png)

I have backported the fixes to release-1.8.x via https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/679 and https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1310. The changes haven't been deployed to production yet as of now.

#### Environment tested

- Browser: Chrome (Desktop - Ubuntu)
- Mode: Local & Dev (https://dev.open-paas.org)

#### What needs to be done

- [ ] The fixes need to be deployed to https://openpaas.linagora.com.

**Comment by hantt12** [comment]
Passed QA for event invitation/update/cancellation
Need to update on Notification email too (created the new issue for tracking: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/150 )
