### ISSUE TITLE
The datetime format is not translated correctly in the calendar event bluebar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#113]
#### Steps to reproduce

- As **User B**:

  1. Login and go to Control Center.
  2. Change your language to something else other than English (let's say Vietnamese - Tiếng Việt).

- As **User A**:

  1. Login and go to the Calendar SPA
  2. Create a new event and add **User B** as an attendee.

- As **User B**:

  1. Go to the Inbox SPA
  2. Go to the INBOX folder
  3. Open the equivalent invitation mail

##### Current behaviour

The date & time are not translated to **User B**'s selected language (and his selected datetime format).

See in the picture below, the datetime format is in English while the selected language is Vietnamese.

![image](https://user-images.githubusercontent.com/24670327/93755409-6f583100-fc2d-11ea-97ff-7dfacfaf04a9.png)

##### Expected behaviour

The date & time should be translated to **User B**'s selected language (and his selected datetime format).

**Comment by asmaNode** [comment]
@huy-ta Date and time format  depend on timezone not the selected language , No ?

**Comment by huy-ta** [comment]
@asmaNode No, the date & time format depends on the locale (the selected language) of the user. For example, when you go to Shanghai, China, the timezone should be, of course, Asia/Shanghai, but the date time format is not in Chinese. The date time format will always depend on the selected language of the user.

**Comment by asmaNode** [comment]
this is the fix : https://github.com/OpenPaaS-Suite/esn-frontend-inbox-calendar/pull/15

**Comment by asmaNode** [comment]
# Definition of Done

## Done
- Translate datetime of started event in eventbluebar with the locale language of user

**Comment by hantt12** [comment]
I can always reproduce without any specific steps
![Screenshot 2020-10-21 11:27:42](https://user-images.githubusercontent.com/53081477/96673323-768b6f80-1390-11eb-879b-33db413658cd.png)
