### ISSUE TITLE
Provide a way to share calendar as ICS url

### ISSUE THREAD

**Issue by tanandy** [OpenPaaS-Suite/esn-frontend-calendar#114]
in the past OBM allowed to share Ical calendar to ICS format as public/private url that is different from ICS export

![image](https://user-images.githubusercontent.com/18187444/93765124-aa019f80-fc14-11ea-9cb5-d24a99bcdf76.png)

we could add this settings on the calendar settings, then we could provide ics url by calendar

![image](https://user-images.githubusercontent.com/18187444/93765195-c69dd780-fc14-11ea-9eb1-6b025296286d.png)

this feature exists on different suites like google calendar, outlook.com etc...

google calendar
![image](https://user-images.githubusercontent.com/18187444/93765970-074a2080-fc16-11ea-930a-9871f9a5dc63.png)

outlook.com
![image](https://user-images.githubusercontent.com/18187444/93766082-2ba5fd00-fc16-11ea-8bca-87c5c8abb26b.png)

**Comment by tanandy** [comment]
@huy-ta can we create a user story / design for this one :)

**Comment by huy-ta** [comment]
Closed this in favour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/225.
