### ISSUE TITLE
Allow users to duplicate events

### ISSUE THREAD

**Issue by tanandy** [OpenPaaS-Suite/esn-frontend-calendar#115]
Currently we have no way to duplicate event in calendar.

we would like to have the possibility to duplicate event through a  custom context menu or in a dedicated popin for example

**Comment by huy-ta** [comment]
Hi, I think we are going to implement this feature soon. I'm going to write a user story for this to make sure the feature is analyzed & understood correctly.

**Comment by huy-ta** [comment]
Closed in favour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/222.
