### ISSUE TITLE
"See in calendar" link in event mail opens the incorrect location

### ISSUE THREAD

**Issue by piavgh** [OpenPaaS-Suite/esn-frontend-calendar#118]
![Screenshot](https://user-images.githubusercontent.com/4060207/93840248-fd79f900-fcb9-11ea-911e-934e97ab36a4.png)

**Comment by rezk2ll** [comment]
@piavgh can you please explain what is wrong with the location?

currently, in dev it opens the following link in calendar SPA:

https://dev.open-paas.org/calendar/#/calendar?viewMode=agendaWeek&start=2020-09-21&end=2020-09-28

**Comment by piavgh** [comment]
Hi @rezk2ll 
As I tested on my localhost, currently, it opens http://localhost:8080/calendar/#/calendar?start=09-21-2020
But the correct link for my localhost should be http://localhost:9900/calendar/#/calendar?start=09-21-2020

Someone in Feedback OpenPaaS channel had this issue on production:

> When we receive an invit to an event by email on OpenPaas, the "see on calendar" link sends on the OpenPaaS inbox and not on the calendar.

**Comment by rezk2ll** [comment]
so we need to provide the backend a way to know where the calendar SPA is.

we can use:
**solution 1** the application discovery service ( no configuration stored for now )
**solution 2** env variables

what do you think @tuanlc @huy-ta @piavgh? do you propose another solution?

**Comment by rezk2ll** [comment]
just for information, we get the baseUrl using this helper:

```js
var STATIC_BASE_URL = url.format({
  protocol: 'http',
  hostname: 'localhost',
  port: staticConfig.webserver.port || '8080'
});

function getBaseUrl(user, callback) {
  return esnconfig('web').forUser(user).get(function(err, web) {
    if (err) {
      return callback(err);
    }

    if (web && web.base_url) {
      return callback(null, web.base_url);
    }

    return callback(null, STATIC_BASE_URL);
  });
}
```

**Comment by tuanlc** [comment]
The invitation email template is built at the backend side, so we can provide:
- Quick fix: by adding `/calendar` in the baseURL in the link. For example:
  - BaseURL: https://openpaas.linagora.com
  - Then baseURL of the link: https://openpaas.linagora.com/calendar
- Long term fix: use application discovery service to config SPAs. Then use their baseURLs.

**Comment by rezk2ll** [comment]
@tuanlc it is already the case since the merge of [this pull request](https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/669/diffs).

the changes are working in dev but not in production.

**Comment by tuanlc** [comment]
> @tuanlc it is already the case since the merge of [this pull request](https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/669/diffs).
> 
> the changes are working in dev but not in production.

Cool! We need to release a new version and deploy it to production. Ask @MichaelBailly for the approval.

**Comment by tuanlc** [comment]
@rezk2ll did you backport the fix to branch `release-1.8.x`?

**Comment by rezk2ll** [comment]
> @rezk2ll did you backport the fix to branch `release-1.8.x`?

done

**Comment by huy-ta** [comment]
@rezk2ll Please write a DoD for this and then ask the QA team to test it (fast). Example DoD: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/112#issuecomment-701208192.

**Comment by rezk2ll** [comment]
# Definition of Done
- while in inbox SPA, and after opening an event invitation link:
    - the *see in calendar* link should open the calendar SPA

![image](https://user-images.githubusercontent.com/6764881/94661122-8dddbc80-02fe-11eb-93d1-bfe2bd56ea16.png)


**What has been done by me**
- fixed the issue in [gitlab](https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/669/diffs)
- backported to the `1.8.x` release.

**what is missing**
- deploy the changes to production
