### ISSUE TITLE
[Sabre] call to getChildren() of null

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#124]
Please refer to https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/issues/65.

**Comment by MichaelBailly** [comment]
Hi there. I understand that we have to fix the caller (client), however we also have to strengthen the SERVER code so it doesn't throw an exception and handles the case gracefully (certainly by returning a 400 error if that is a client arguments problem)

**Comment by rezk2ll** [comment]
PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/266

**Comment by huy-ta** [comment]
@rezk2ll This is a very technical issue. The QA team will have no idea what the issue is to even begin with. What you need to do is describing what impacts the PR might have so that the QA team can do some kind of regression tests.
