### ISSUE TITLE
When creating event, focus should be set on event title

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#127]
![NewEventModelFocus](https://user-images.githubusercontent.com/13099240/93895080-b6a6f600-fcef-11ea-9f61-a3fe57aee21a.png)

**Comment by rezk2ll** [comment]
# Definition of Done

- while in Calendar SPA and after creating or editing an event:
  - the focus should be set on the title field

**Comment by tuanlc** [comment]
@rezk2ll  Nice, you are writing `Definition of Done`  for issues, however:
- The issue should be closed by QA or BA. You should add `QA:testing` label and reopen the issues
- Please follow the DoD template: https://github.com/linagora/openpaas-esn/wiki/Definition-Of-Done
