### ISSUE TITLE
As a user, I want to have a button to copy the video conference link

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#132]
#### User story summary

As a user, I want to have a button to copy the video conference link so that I can get the link quickly just by clicking the button.

#### Criteria

- [x] There are two buttons: One to join the video conference and the other to copy the video conference link to the clipboard.
- [x] When I click the "JOIN THE VIDEO CONFERENCE" button, a new window (e.g. browser tab) will be opened and redirected to the video conference app.
- [x] When I click the "COPY LINK" button, the link (url) to the video conference will be copied to my clipboard.
- [x] The "JOIN THE VIDEO CONFERENCE" should precede the "COPY LINK" button.
- [x] The "JOIN THE VIDEO CONFERENCE" button should be highlighted more than the "COPY LINK" button.
- [x] The text inside the two buttons should display properly (with ellipsis) on smaller mobile devices.

#### UI/UX Design

- On desktops/laptops/tablets:

![image](https://user-images.githubusercontent.com/24670327/94124840-ba698280-fe7f-11ea-9b52-59e027ffe703.png)

- On mobile devices:

![image](https://user-images.githubusercontent.com/24670327/94124247-f819db80-fe7e-11ea-8486-00d95310223f.png)

- On smaller mobile devices:

![image](https://user-images.githubusercontent.com/24670327/94124557-59da4580-fe7f-11ea-9b65-395e27786931.png)

#### Technical notes

- The icons are `mdi-open-in-new` and `mdi-content-copy`.

**Comment by rezk2ll** [comment]
we need to decide what method we are going to use to write to the clipboard when we click on the copy button.

we have 2 options:

**option 1** : use the old [document.execCommand('copy')](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). i made a [draft](https://github.com/OpenPaaS-Suite/esn-frontend-videoconference-calendar/pull/12) using this method.

this method is supported by all browsers but it is considered as an obselete feature and might get removed at some point in the future.

![image](https://user-images.githubusercontent.com/6764881/94189399-979c9580-fea2-11ea-8ac4-b6c137ac24a7.png)


**option 2**: use the new [Clipboard.writeText()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#Browser_compatibility).

this method for security reasons only works on HTTPS served websites ( this means we can't expect this to run on dev or test environment served over regular HTTP ) and also it is only supported by newer browsers and **not** supported by `Internet Explorer`.

![image](https://user-images.githubusercontent.com/6764881/94190111-928c1600-fea3-11ea-9c02-e0802bad1a75.png)


so do you guys think? @tuanlc @renaudboyer @huy-ta @MichaelBailly

**Comment by tuanlc** [comment]
Hi @rezk2ll 
 Copy to clipboard feature already implemented in Calendar which allows users to copy calendar address
![Screenshot_2020-09-25_08-47-02](https://user-images.githubusercontent.com/7950991/94217228-b3885180-ff0b-11ea-91eb-4e1b4c8df7fb.png)

And seem we are using [ngClipBoard](https://sachinchoolur.github.io/ngclipboard/)

**Comment by rezk2ll** [comment]
Thanks tuan

**Comment by huy-ta** [comment]
@rezk2ll Please write a DoD for this.

**Comment by rezk2ll** [comment]
# Definition of Done

- while in calendar SPA, after editing or creating a new event:
  - after selecting a video conference option two buttons should appear
![image](https://user-images.githubusercontent.com/6764881/94661737-5cb1bc00-02ff-11eb-8a24-85525a234acd.png)

  - the `join video conference` button should open the video conference link in a new tab
  - the `copy video` button should copy the video conference link to the user clipboard

**Comment by hantt12** [comment]
Not good UI on small mobile screen

![20200930_3](https://user-images.githubusercontent.com/53081477/94670498-d3b97580-033c-11eb-975c-711ebcebb3d4.png)

Suggestion: use short text like Join and Copy, or use only icons in Mobile devices

**Comment by rezk2ll** [comment]
@huy-ta wdyt?

**Comment by huy-ta** [comment]
Yes, the suggestion from Ha sounds good. Let's do it that way. But I'll create an issue just for that. For now the issue "...to have a button to copy the video conference link" is resolved. @hantt12 

_issue to be updated here_
