### ISSUE TITLE
Default `My agenda` agenda is not translated in shared calendar  sidebar section

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-calendar#133]
#### CURRENT

![Capture d’écran de 2020-09-24 14-18-35](https://user-images.githubusercontent.com/11298249/94143976-db76a700-fe70-11ea-877a-ea3428fe1639.png)

#### EXPECTED

![Capture d’écran de 2020-09-24 14-40-08](https://user-images.githubusercontent.com/11298249/94146198-e121bc00-fe73-11ea-892f-dff838db4874.png)

**Comment by huy-ta** [comment]
If you subscribe to a calendar of a user that uses English, this is the expected behaviour. So I don't think is is a bug and I'll close it for now.
