### ISSUE TITLE
The event details form for the attendees should not have a "Cancel" button

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#136]
#### Steps to reproduce

- As **User A**:

1. Go to the Calendar SPA
2. Create a new event with **User B** as an attendee (name it something like "Test event")

- As **User B**:

1. Go to the calendar SPA
2. Open the "Test event" event above

#### Current behaviour

There's a "Cancel" button which is quite confusing for the user. The button doesn't cancel anything but just closes the event details dialog. The user will likely think that when clicking the "Cancel" button, it will cancel all the actions the user has done (e.g. accepting the event).

![image](https://user-images.githubusercontent.com/24670327/94222431-8772cd80-ff17-11ea-80c1-63e5b5a6fd06.png)

#### Suggested behaviour

The event details form for the attendees should have a "Close" button instead of "Cancel".

**Comment by piavgh** [comment]
## DoD:

When the user opens the event form, the old "Cancel" button should be replaced by "Close" button
