### ISSUE TITLE
New event display is broken sometimes

### ISSUE THREAD

**Issue by tanandy** [OpenPaaS-Suite/esn-frontend-calendar#144]
Seems the email template can be broken in some conditions

![image](https://user-images.githubusercontent.com/18187444/94433968-573a6180-0199-11eb-85fd-4527844cc986.png)

username icon is behind the text and not to the right

**Comment by huy-ta** [comment]
Will be fixed by https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/234.
