### ISSUE TITLE
As a user, I want the Calendar configuration screen to display in a dialog on desktop so that it does not display together with the left sidebar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#147]
<h4 id="definition">User story summary</h4>

As a user, I want the Calendar configuration screen to display in a dialog on desktop so that it does not display together with the left sidebar.

<h4 id="definition">Where to find the feature</h4>

- I login and go to Calendar
- I select "Manage calendars" in the sidebar

<h4 id="criteria">Criteria</h4>

- [x] The Calendar configuration screen should display inside a dialog.
- [x] The dialog should stand out from the rest of the viewport (as seen in the screenshots below).
- [x] The "Shared calendars" section should display the "You have no shared calendars." text if there's no shared calendars.
- [ ] On desktop, the "Color" selector in the "Calendar configuration" screen (when configuring a specific calendar) should open a popover instead of a dialog to avoid dialog overlapping (see the third screenshot below). The old behaviour will be kept for mobile devices.
- [ ] There will be no "Save" button. Any changes will be saved immediately. There should be a 500ms debounce for changes in a calendar's title.

<h4 id="design">UI/UX Design</h4>

1. [Desktop] The main "Manage calendars" screen:

![calendar_config_dialog](https://user-images.githubusercontent.com/24670327/94406889-e85f0780-019c-11eb-96f8-47b6e8c682ba.png)

2. [Desktop] The "Calendar configuration" screen (when configuring a specific calendar):

![calendar_config_dialog_2](https://user-images.githubusercontent.com/24670327/94407536-c0bc6f00-019d-11eb-89f9-19e9c3b2f0d6.png)

3. [Desktop] The color picker in the "Calendar configuration" screen (when configuring a specific calendar):

![calendar_configuration_dialog_color_picker](https://user-images.githubusercontent.com/24670327/94643243-8fb07b80-0310-11eb-9c64-56ef3d63b710.png)

**Comment by huy-ta** [comment]
@pbson Please write a DoD for this.

**Comment by pbson** [comment]
## Definition of Done

#### What I have done

I have resolved this issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/147.
1. Now the Calendar configuration screen is displayed in a dialog on desktop so that it does not display together with the left sidebar. Here's the result:
Demo: https://streamable.com/nhaphp

2.When there are no shared calendar, the text 'You have no shared calendars' will be display

3. The "Color" selector in the "Calendar configuration" screen can be saved automatically when user choose a color, without having to press save button

4.Changes in the "Display" Tab in the "Manage calendar" screen is now saved automatically when user make a change, the screen will be refreshed when user close the modal or change to "Calendar" tab.
#### Environments tested

- Browser: Chrome & Firefox Desktop (Ubuntu)
- Mode: Dev (on the local computer)
- Mobile: Ipad, Iphone 5s, Android 11

**Comment by hantt12** [comment]
1. Bug https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/243
2. Can user see the change without clearing the cache? As I tested in my Chrome, I have to clear cache to see it

**Comment by huy-ta** [comment]
> 1. Bug #243
> 2. Can user see the change without clearing the cache? As I tested in my Chrome, I have to clear cache to see it

3. When the user selects a calendar and then reloads the page, the reloaded page displays a dialog with an empty calendar (which is not expected).

**Comment by huy-ta** [comment]
@pbson I'll temporarily revert this PR until we can fix all the issues so that we don't accidentally deploy a feature with some bugs.

**Comment by huy-ta** [comment]
> ## Definition of Done
> #### What I have done
> I have resolved this issue via #147.
> 
> 1. Now the Calendar configuration screen is displayed in a dialog on desktop so that it does not display together with the left sidebar. Here's the result:
>    Demo: https://streamable.com/nhaphp
> 
> 2.When there are no shared calendar, the text 'You have no shared calendars' will be display
> 
> 1. The "Color" selector in the "Calendar configuration" screen can be saved automatically when user choose a color, without having to press save button
> 
> 4.Changes in the "Display" Tab in the "Manage calendar" screen is now saved automatically when user make a change, the screen will be refreshed when user close the modal or change to "Calendar" tab.
> 
> #### Environments tested
> * Browser: Chrome & Firefox Desktop (Ubuntu)
> * Mode: Dev (on the local computer)
> * Mobile: Ipad, Iphone 5s, Android 11

Here's the DoD in case you need it.

**Comment by hantt12** [comment]
the dialog does not look nice in Delegation tab, in both Mobile and Desktop view
please check https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/380
