### ISSUE TITLE
Email group invitation problem when inviting an event with lots of people

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#148]
When you add an email group as an attendee, all the people in that group might not be able to receive an invitation email when there are more than 50 people in that group. In fact, only the first 50 users will be invited to the event. 

This is likely a performance issue or a group denormalization issue when there are a lot of attendees (for the case of team-paris@linagora.com, about nearly 100 people). This certainly needs to be improved as in a real-world scenario there'll be a lot more (maybe thousands). And it needs to be resolved FAST as it is affecting the daily worklife of our users at Linagora.

**Comment by huy-ta** [comment]
It turns out that the group denormalization logic in our backend code is wrong and doesn't respect `limit=0`. Check out: https://github.com/OpenPaaS-Suite/esn/issues/37.

**Comment by huy-ta** [comment]
Here's the fix: https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1312.

**Comment by huy-ta** [comment]
## Definition of Done

#### What I have done

I have resolved the email group issue via https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1312. Now when adding an email group with more than 50 people, all of them will be invited to the event instead of just the first 50 ones like before.

#### Environments tested

- Browser: Chrome (Ubuntu)
- Mode: Local & Dev (https://dev.open-paas.org)

**Comment by tlle14** [comment]
Hi @huy-ta 

I cannot create a correct event using a copy-paste attendees group.

**Comment by huy-ta** [comment]
I have created a separate issue to handle that: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/165.

**Comment by tlle14** [comment]
Hi @huy-ta  @hantt12 

I can create an event with 92 attendees in the mail group. It is able to display all the attendees in the event details. 

![image](https://user-images.githubusercontent.com/69950655/95301103-55178780-08aa-11eb-8e55-f437a58282d3.png)

**Comment by tlle14** [comment]
But there are 2 problems:

1. It takes a long time for creating the event successfully and display on the calendar (about 1-2 mins)

2. Cannot create an event when the group has about 200 members. It returns status code 504 Gateway time-out

**Comment by huy-ta** [comment]
> But there are 2 problems:
> 
> 1. It takes a long time for creating the event successfully and display on the Organizer's calendar (about 1-2 mins)
> 2. Cannot create an event when the group has about 200 members. It returns status code 504 Gateway time-out

The Calendar team will continue to handle this in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/182.
