### ISSUE TITLE
time in notification (alarm) email is always shown in UTC

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#150]
Steps:

1. Usera goes to account settings and selects a timezone
2. Userb invites usera to an event and set an alarm
3. Ntofication (alarm) email is sent to usera when the time comes
4. Check the timezone of the event time in the notification email

Expected result:
Time should be displayed in usera's selected timezone

Actual result:
Time is shown in UTC 

![20200930_1](https://user-images.githubusercontent.com/53081477/94662009-014cf180-0332-11eb-87d3-80094b61ef4c.png)

**Comment by asmaNode** [comment]
can not reproduce the bug @hantt12 , can you confirm that this bug still exist 
![timeUTC](https://user-images.githubusercontent.com/43316837/95109170-24154680-0734-11eb-9868-66f030021dfd.png)

**Comment by hantt12** [comment]
I can always reproduce it without specific steps

![Screenshot 2020-10-21 11:27:42](https://user-images.githubusercontent.com/53081477/96673646-27920a00-1391-11eb-9b2d-4582b92a1de2.png)
