### ISSUE TITLE
As a user, I want the "Join the video conference" button and the "Copy link" button to display in a better way in mobile devices

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#152]
#### User story summary

As a user, I want the "Join the video conference" button and the "Copy link" button to display in a better way in mobile devices.

#### Criteria

- [x] When displayed in mobile devices, the text should change from "Join the video conference" to "Join now" to avoid cropped text.

#### UI/UX Design

![videoconference_mobile](https://user-images.githubusercontent.com/24670327/96567652-3cb75c00-12f1-11eb-95b3-4202a6b178ba.png)

**Comment by pbson** [comment]
## Definition of Done

#### What I have done

I have resolved this issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/152

1. Now the button "Join the video conference" will become "Join now" on mobile device to avoid cropped text.
2. Add translation for newly added text "Join now"

- Browser: Chrome & Firefox Desktop (Ubuntu)
- Mode: Dev (on the local computer)
- Mobile: IOS, Android
