### ISSUE TITLE
As a user, I want the more important fields to precede the less important fields in the event dialog

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#155]
#### User story summary

As a user, I want the more important fields to precede the less important fields in the event dialog as they are much more frequently used.

#### Where to find the feature

1. Go to Calendar
2. Choose to create a new event or edit an existing event
3. The event dialog should be opened

#### Criteria

- [x] The "Attendees" and the "Resources" fields should follow the date/time fields and precede all the other fields.

#### UI/UX Design

- On desktop/laptop:

![image](https://user-images.githubusercontent.com/24670327/94800114-565e3580-040e-11eb-88c5-296ab15411a4.png)

- On mobile devices:

![image](https://user-images.githubusercontent.com/24670327/94800076-4d6d6400-040e-11eb-8217-7217b7480009.png)

**Comment by rezk2ll** [comment]
# Definition of done
- when creating/editing an event
  - the `attendees` field should appear right below the time fields.
  - the `resources` field should appear right below the `attendees` field and before the rest of the fields.

**Comment by huy-ta** [comment]
@rezk2ll That is not how DoD is written. It should look like below:

## Definition of Done

#### What I have done

I have resolved this issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/156. Now, when opening the event dialog (when creating or editing an event), the "Attendees" field and the "Resources" field will follow the date time fields and precede the all the other fields.

Here's the screenshot of the result on desktop:

![image](https://user-images.githubusercontent.com/24670327/94912428-d4374500-04d1-11eb-8546-52221b6e5d49.png)

#### Environments tested

- Browser: Chrome Desktop (Ubuntu)
- Mode: Dev (Local & https://dev.open-paas.org)
