### ISSUE TITLE
Update OpenPaas dev environment for Sabre Dev

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#167]
Update common OpenPaas dev environment to allow Sabre development.

Common dev environment repo is [here](https://ci.linagora.com/linagora/lgs/openpaas/openpaas-platform-docker-dev/)

We need to add a Sabre dev mode that uses user local source directory as done in OpenPaas docker-compose [here](https://github.com/linagora/openpaas-esn/blob/master/docker/dockerfiles/dev/docker-compose-sabre-dev.yml#L39)

**Comment by huy-ta** [comment]
@renaudboyer @thebtililya What is the status of this issue? Can I close it now?

**Comment by renaudboyer** [comment]
@huy-ta We may eventually change the platform so updating current dev env is not relevant anymore.

So we can close it.
