### ISSUE TITLE
As a user, I want all the declined events to hide, no matter where they come from, when I have configured my calendar display settings to do so

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#173]
#### User story summary

As a user, I want all the declined events to hide, no matter where they come from, when I have configured my calendar display settings to do so.

#### Steps to reproduce

- As User A:

1. Login and go to Calendar
2. Share your default calendar ("My agenda") to User B with the "See all event details" permission
3. Decline an event (you need to be part of an event first). Let's assume the event's title is "Test event"

- As User B:

1. Login and go to Calendar
2. Verify that you are able to see "Test event" with strikethrough (because User A has declined it)
3. Go to "Manage calendars > Display", choose the option to hide declined events.

#### Current behaviour

User B is still able to see the declined event ("Test event") in the calendar shared by User A.

#### Expected behaviour

User B should not be able to see any declined event, no matter where it comes from (so "Test event" should not be displayed in User B's calendar view).

**Comment by piavgh** [comment]
## DoD:

User B should not be able to see any declined event, no matter where it comes from (so "Test event" should not be displayed in User B's calendar view).
