### ISSUE TITLE
Time picker hasn't been updated in the propose new time in the invitation email

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#179]
# Actual Result

When an attendee opens the invitation mail > click "see event details" > choose "propose a new time", the time picker is still an old version.

![95298298-1089ed00-08a6-11eb-8abf-83066d820a9b](https://user-images.githubusercontent.com/69950655/95309507-6e720100-08b5-11eb-8149-18047f0c430b.png)

# Expected Result

The Time picker should be updated in the whole system

# Environment

DEV Environment

**Comment by rezk2ll** [comment]
# Definition of Done

## Done
- replaced the old clock picker component with the time select component when in `Propose a new time` dialog.
