### ISSUE TITLE
System doesn't accept manual input "SA/CH" (as AM/PM in Vietnamese) in the time textbox

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#181]
# Actual Result

When the language is Vietnamese, time textboxes doesn't allow the user to manually input text `SA` (as AM) or `CH` (as PM) in the time textboxes.
![Peek 2020-10-07 12-13](https://user-images.githubusercontent.com/69950655/95311641-125cac00-08b8-11eb-8c8c-5dccc7cd18bb.gif)

# Expected Result
When the language is Vietnamese, the user should be able to manually input text `SA` or `CH` in the time textboxes.

# Environment 
Dev Environment

**Comment by rezk2ll** [comment]
# Definition of Done

## Done
- Fixed the time select ignoring the (night/day) suffix when in non-english locales.
