### ISSUE TITLE
[Sabre] Performance issue when inviting a lot of attendees

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#182]
#### Current issue

When you add an email group with a lot of people (let's say, 100+), the event creation process takes too long and most of the time there'll be a timeout error.

#### Possible causes

1. The timeout setting in Sabre might be a little bit short.
2. Currently, the event creation process **includes** sending invitation emails to all the attendees. The invitation emails are sent even before the event is created in the organizer's calendar (before the request is completed). So, the attendees might receive emails and have the event in their calendars, but the event creation process might experience timeout and the event will never be created in the organizer's calendar. Therefore, the attendees might sometimes see the event but the organizer doesn't.

#### Suggested solutions

1. [Extend the timeout](https://ci.linagora.com/mbailly/esn-sabre/merge_requests/new/diffs?merge_request%5Bsource_branch%5D=php-max-time). However, this does not really solve the root problem because the timeout is fixed while the number of attendees can be whatever large.
2. IMO, the event creation flow should be changed. The flow should be something similar to what we're doing with Elasticsearch:
- Create the event first, and then the request is completed. Inform the user that the event has been created.
- Afterwards, send the emails to the attendees.

So the invitation emails will no longer be part of the event creation process, and will be executed later after the event has been successfully created.

**Comment by huy-ta** [comment]
@MichaelBailly @renaudboyer What do you think?

**Comment by huy-ta** [comment]
I'll first extend the request timeout: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/257.

This doesn't go to the root of the problem, however. We'll need to discuss more.

**Comment by huy-ta** [comment]
## Definition of Done

#### What I have done

I have extended the request timeout from 30s to 120s (2 minutes) when creating/updating/deleting an event via https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/257. Now an event with roughly 100 attendees will be properly created (though it will still take quite some time).

##### Environment(s) tested

- Environment: Tested on the local environment with dev mode.
- Browser: Chrome Desktop (Ubuntu)

**Comment by tlle14** [comment]
Retest pass with the 100+ members group but fail immediately with 200+ members group.
![Peek 2020-12-02 15-52](https://user-images.githubusercontent.com/69950655/100850476-6fd73880-34b6-11eb-94d5-497f466e321f.gif)
