### ISSUE TITLE
disable the time select when the user can't modify the event

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-calendar#184]
**currently**:

- when a non-event organizer ( just an event viewer ) opens an event the time select component is not disabled ( picking time has no effect )

**expected**:

- the time select should be disabled when the user has no permission to edit the time or the event.

**Comment by rezk2ll** [comment]
# Definition of Done

## Done
- fixed the time select component not being disabled when the user can't edit the event.

**Comment by hantt12** [comment]
As far as I can see, user is still able to select time when he is not organizer

![Peek 2020-10-15 16-12](https://user-images.githubusercontent.com/53081477/96103004-5d527100-0f01-11eb-9091-fe54efd02dd3.gif)

Tested today on Dev platform

**Comment by rezk2ll** [comment]
dunno what changed from last time, but i made a fix for it https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/211
