### ISSUE TITLE
Fix template import

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-calendar#2]
As explained [here](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Week-by-Week-Activity#check-the-templateurl-calls-no-html-template-should-be-served-from-the-backend), fix the PUG template imports.

```
In the task moving from "templateUrl: string" to "template: require('pugfile')"

The templateUrl has not been changed for path /calendar/app/search/event/event-search-item.html. This would break application.
```

**Comment by tuanlc** [comment]
I reopen this issue because you only fix for templateUrl places but not for dynamic templates that pass by element attribute.
Please check my PR description and code to see more: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/7
