### ISSUE TITLE
Event invitation message only shows the master event's details when updating a recurrence exception

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#206]
#### Steps to reproduce

- As **User A**:

1. Log in and go to Calendar
2. Choose to create an event with the title "Daily event", make it an endless daily event, and invite **User B**
3. Save the event
4. Update the title & time of a occurrence (thus, making it a recurrence exception)

- As **User B**:

1. Log in and go to Inbox
2. Check the last email related to "Daily event"

#### Current behaviour

The email does not inform **User B** about the update details of the recurrence exception. Instead, it only shows the details of the master event.

#### Expected behaviour

The email should inform **User B** about the update details of the recurrence exception.

#### Suggested solution(s)

> When OpenPaaS sends a REQUEST related email to event attendees, on a recurring event when an occurrence is detached (bc it's not the same time, or the same title...), Sabre sends the ICS of the full event, which means the master event, and all the detached occurrences, as a collection of VEVENTs.
>
> I tracked the commit and came to commit https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/commit/15c90e87da278b4566368a7649a95718b3a61ad6. WARNING: I'm not so sure that this is the correct commit, because you know, Sabre code is complicated.
>
> This has impacts on several levels, the worst one being that the emails, sent to attendees, contains wrong information when a detached occurrence changes: the information is always the one of the master event.
>
> I did test GSuite and O365: both of them send only the detached occurrence VEVENT.
>
> I remember that we also used to send only the detached occurrence, and I cannot remember why we switched, other than it was related to some external product support.

(_from @MichaelBailly_)

There are two simple solutions:

1. Only send the detached occurrence VEVENT and make sure the associated email content is good.
2. Keep sending the ICS of the full event, and make sure the associated email content is correct by extracting the information from the recurrence exception instead of the master event.

**Comment by huy-ta** [comment]
This might be related to https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/154.

**Comment by asmaNode** [comment]
@huy-ta @MichaelBailly 
Investigating on this bug , I guess the origin of this error is that we always send the first vevent 
```js
function getIcalEvent(icalendar) {
  const vcalendar = ICAL.Component.fromString(icalendar);
  //====>Check this line
  const event = vcalendar.getFirstSubcomponent('vevent');
  const icalEvent = new ICAL.Event(event);
  const timezones = _.chain(vcalendar.getAllSubcomponents('vtimezone')).map(ICAL.Timezone.fromData).keyBy('tzid').value();

  if (icalEvent.startDate) {
    icalEvent.startDate.zone = timezones[icalEvent.startDate.timezone] || icalEvent.startDate.zone;
    if (icalEvent.endDate) {
      icalEvent.endDate.zone = timezones[icalEvent.endDate.timezone] || icalEvent.endDate.zone;
    }
  }

  return icalEvent;
}
```
So my proposal solution is to send the last vevent found ( i tested and it works you can check the draft)
```js
 const vevents = vcalendar.getAllSubcomponents("vevent");
 const event= vevents[vevents.length-1];
```

**Comment by asmaNode** [comment]
DEMO
![updateEvent](https://user-images.githubusercontent.com/43316837/96017305-c377bf00-0e41-11eb-9466-54fa25716aba.gif)

**Comment by asmaNode** [comment]
https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/684

**Comment by huy-ta** [comment]
@asmaNode You need to discuss with Renaud to find out why this PR exists: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/60.

**Comment by asmaNode** [comment]
cc @renaudboyer

**Comment by renaudboyer** [comment]
We use Sabre schedule hook to send email notification. 
This hook is used to update each attendee's event copy when someone update an event
This hook always sends whole event (with master and exceptions).

This commit will only split whole message into one message per event if there are master + instances VEVENT so email will contain only one VEVENT per email.

To fix this problem, we need to remove unmodified VEVENT from the message.
This can be achieved by comparing VEVENT with previous version.

**Comment by asmaNode** [comment]
PR : https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/684

**Comment by asmaNode** [comment]
I will leave this issue waiting for the real fix

**Comment by huy-ta** [comment]
This should be fixed via https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/261.

**Comment by hantt12** [comment]
stil the same as before in dev platform as I check this morning @huy-ta
