### ISSUE TITLE
Notification is not shown smoothly on Android mobile/Chrome

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#208]
Steps to reproduce:

Tested on Samsung A5/Chrome

1. Go to calendar
2. Create a new event >> Save
3. Check how the message is shown

Current behavior:
The message is not shown smoothly

[20201014_151905.zip](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/files/5376756/20201014_151905.zip)

**Comment by huy-ta** [comment]
This is due to the virtual keyboard of the phone closing a little bit too slowly, causing the screen height to "flicker", thus the not-so-smooth messages. I don't think we will be able to fix this.
