### ISSUE TITLE
No message when delegated user accepts/declines events

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#210]
Steps to reproduce:

1. User A shares his default calendar (My Agenda)to User B with Edit event and manage sharing permission

2. User C invites user A to an event

3. User B clicks on the above event from user A's shared calendar

4. User B clicks Accept/Decline option

Expected result:
Message should be shown at the bottom of the page (message content to be defined)

Actual result:
No message is shown

This may not be a bug but an improvement. I will assign to BA (Huy) for consideration

**Comment by rezk2ll** [comment]
this bug is fixed
