### ISSUE TITLE
Javascript error on Calendar module

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#213]
This issue occurs everytime user takes any actions on Calendar module
![2020-10-19_14-01](https://user-images.githubusercontent.com/53081477/96411982-93e6ff00-1213-11eb-841a-644436320872.png)

**Comment by rezk2ll** [comment]
code showing the error:
```js
        scope.stop = function() {
          if ( !scope.spinner ) { return ; }
          element[0].removeChild(scope.spinner);
        };
```

file : esn-frontend-common-libs/src/frontend/components/openpaas-logo/openpaas-logo.js
