### ISSUE TITLE
As a user, I want the event invitation email to display nicely in mobile devices

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#217]
#### User story summary

As a user, I want the event invitation email to display nicely in mobile devices as currently half of the content is cropped.

#### Criteria

- [ ] All of the content of the email should be visible.
- [ ] The content of the email should be arranged in a nice way. I'll leave the assignee of this issue to decide how it should be arranged.

**Comment by MichaelBailly** [comment]
Please do not fix the existing templates, better replace them with the new ones that Phuong created. 

By the way I saw this this weekend https://mjml.io/

**Comment by huy-ta** [comment]
Mh... The ones Phuong created do not include mobile devices though. I'll need to make this clearer before anyone takes on this issue. cc @rezk2ll

**Comment by huy-ta** [comment]
Closed in favour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/234.
