### ISSUE TITLE
[STORY] Hide the calendar sidebar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#218]
#### Definition

As a user, I want to hide the calendar sidebar to have the agenda full screen.

#### Criteria

- [x] There should be a button to toggle the sidebar on the left side of the subheader with the menu icon (`mdi-menu`).
- [x] When clicking on the icon and the sidebar is currently shown, the sidebar should be hidden and the agenda view expands to occupy the full width of the screen.
- [x] When clicking on the icon and the sidebar is currently hidden, the sidebar should be shown.
- [ ] When hovering over the icon, there should be a hover effect and a tooltip - "Toggle sidebar".
- [ ] (Optional) There should be a smooth animation transition when toggling the sidebar.

#### UI/UX Design

- The default view (the sidebar is shown):

![toggle-sidebar-design-1](https://user-images.githubusercontent.com/24670327/96669305-24921c00-1387-11eb-985f-8053abdfe464.png)

- The sidebar is hidden:

![toggle-sidebar-design-2](https://user-images.githubusercontent.com/24670327/96668998-9027b980-1386-11eb-99ed-adb4bc8eade0.png)

**Comment by pbson** [comment]
## Definition of Done

#### What I have done

I have resolved this issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/218

1. Now there is a toggle button on the left side of the subheader with the menu icon. When the left sidebar is currently shown, clicking on the button will hide the sidebar. And vice versa, when clicking on the icon and the sidebar is currently hidden, the sidebar is shown.

- Browser: Chrome & Firefox Desktop (Ubuntu)
- Mode: Dev (on the local computer)
- Mobile: IOS, Android

**Comment by hantt12** [comment]
Minor issue https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/396
