### ISSUE TITLE
[STORY] Use the native date picker in mobile devices

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#219]
#### Definition

As a user, I want to use the native date picker (when creating/updating an event) in mobile devices.

#### How to find the feature

1. Login and go to Calendar in your mobile device
2. Choose to create a new event
3. Choose the date for the event
4. A date picker will be displayed

#### Criteria

- [x] The native date picker should be used in mobile devices.
- [x] For desktop/laptop devices, the custom date picker should still be used.

**Comment by rezk2ll** [comment]
# Definition of done

### what I did
i resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/252

 - Use the native date picker on mobile devices.
 - Keep the custom date picker for laptop/desktop devices.

### environment
- chrome 86.0.4240.183
