### ISSUE TITLE
The event notification email is wrong when the organizer updates a recurrent event with a busy attendee

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#221]
#### Steps to reproduce

- As **Attendee 1**:

1. Login and go to Calendar
2. Make sure you are attending an event from 03:30 PM - 04:00 PM

- As **Attendee 2**:

1. Login and go to Calendar
2. Make sure you are not attending any event from 03:30 PM - 04:00 PM

- As **Organizer**:

1. Login and go to Calendar
2. Create a recurrent event (be it daily or weekly) from 03:45 PM - 04:15 PM. Invite **Attendee 1** and **Attendee 2**. The title of the event is "Recurrent event"

- As **Attendee 1**:

1. Go to Calendar
2. Accept the "Recurrent event" series (_THIS STEP IS IMPORTANT_)

- As **Organizer**:

1. Go to Calendar
2. Update the "Recurrent event" series (you can update the time, location, description, etc.)

Now go check the emails that have been sent to **Attendee 1** & **Attendee 2**.

#### Current behaviour

- **Attendee 1** & **Attendee 2** both receive an email with title "Event Recurrent event from Organizer canceled". The content of the email is also about the event getting cancelled, with only one attendee, which is the current recipient.
- The events are not updated in the calendars of **Attendee 1** and **Attendee 2**.

#### Expected behaviour

- **Attendee 1** & **Attendee 2** should receive an email about the event being updated instead.
- The events should be updated correctly in the calendars of **Attendee 1** and **Attendee 2**.

**Comment by renaudboyer** [comment]
I've been able to reproduce the same problem with recurring event with one exception.

Once we modify the whole serie, exception are removed and treated as CANCELLED event

Each time, the ICS attached to the email is a CANCEL iTip with a single exception VEVENT

**Comment by MichaelBailly** [comment]
FYI: we started to work on those kind of issues and log behaviour of our competitors

https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/-/wikis/behaviour#recurrences

It would be great to know the behaviour of our competitors, especially when we update the master event start time.

**Comment by renaudboyer** [comment]
Email notification are not correct but the main issue is that events are not properly updated by Sabre.

[This PR](https://ci.linagora.com/linagora/lgs/openpaas/sabre-vobject/merge_requests/17) will fix the Sabre issue and also notifications in some cases.

The problem was the broker was modified to handle email notification but it shouldn't as it manages Sabre scheduling processes.

**Comment by renaudboyer** [comment]
Related to #239

DoD is [here](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/239#issuecomment-720099318)

Regarding this PR:

* it fixes the attendee calendar issues
* Email don't notify cancellation anymore in case of modification of a recurring event

BUT email are not correct in case of exception modification/cancel. As the whole event ICS is sent, OpenPaas process the master event only.
