### ISSUE TITLE
[STORY] Event duplication

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#222]
#### User story summary

1. [Definition](#definition)
2. [Criteria](#criteria)
3. [Screenshots/Pictures](#screenshots)
4. [Other notes](#notes)

<h4 id="definition">Definition</h4>

As a user, I want to be able to duplicate an event (create a new event with the same information of an existing event).

<h4 id="criteria">Criteria</h4>

- [x] There should be an icon button on the left of the footer of the event dialog to allow duplicating the current event (**Picture 1**).
- [x] When there is already the "Delete event" button the left of the footer of the event dialog, the icon button to duplicate the currrent event will be on the right of the "Delete event" button (**Picture 2**).
- [x] When hovering over the icon button, there should be a hover effect and a tooltip: "Duplicate this event".
- [x] When the user clicks on the "Duplicate event" button, the current event dialog will be closed and a new one will be opened with the header's title "Create a new event". Let's refer to this new event dialog as **the event duplication dialog**.
- [x] After **the event duplication dialog** has been opened, all the information from the original event will be copied to this new event form.
- [x] If the original event is from a calendar that the user does not own, the default selected calendar of the new event will be the default calendar of the current user.
- [x] If the user is not the organizer of the original event, he will be come the organizer of the new event, and the organizer of the original event will be one of the attendees of the new event.
- [x] If the original event includes a video conference, the new event will also include a video conference whose link different from that of the original event, just like when adding a video conference to a brand new event.
- [ ] If the original event is a master event of a recurrent series, the new event will also be the master event of a recurrent series with the same recurrent rule.
- [x] If the original event is a recurrent exception of a recurrent series, the new event will be treated as a single normal event with the same information of the recurrent exception.
- [x] If the attendees have accepted/declined/tentatively accepted, their participation status in the new event will be reset back to when they haven't accepted/declined/tentatively accepted.

<h4 id="screenshots">Screenshots/Pictures</h4>

- **Picture 1**: There is an icon button on the left of the footer of the event dialog to allow duplicating the current event:

![image](https://user-images.githubusercontent.com/24670327/96710894-e61c5180-13c6-11eb-9e84-411301e57ef4.png)

- **Picture 2**: When there is already the "Delete event" button the left of the footer of the event dialog, the icon button to duplicate the currrent event is on the right of the "Delete event" button:

![image](https://user-images.githubusercontent.com/24670327/96710462-4fe82b80-13c6-11eb-9b26-5c4765d04e20.png)

<h4 id="notes">Other notes</h4>

- The icon used in the screenshots/pictures is `mdi-library-plus`.

**Comment by huy-ta** [comment]
@tanandy What do you think about this design of the event duplication button?

**Comment by tanandy** [comment]
why not when we dont use custom context menu. it could be also to the right of "Decline button"

**Comment by huy-ta** [comment]
> why not when we dont use custom context menu. it could be also to the right of "Decline button"

This will be temporary until we have a custom context menu and a two-step event dialog.

**Comment by rezk2ll** [comment]
# Definition of Done

### Dev done

- [x] There should be an icon button on the left of the footer of the event dialog to allow duplicating the current event (**Picture 1**).
- [x] When there is already the "Delete event" button on the left of the footer of the event dialog, the icon button to duplicate the current event will be on the right of the "Delete event" button (**Picture 2**).
- [x] When hovering over the icon button, there should be a hover effect and a tooltip: "Duplicate this event".
- [x] When the user clicks on the "Duplicate event" button, the current event dialog will be closed and a new one will be opened with the header's title "Create a new event". Let's refer to this new event dialog as **the event duplication dialog**.
- [x] After **the event duplication dialog** has been opened, all the information from the original event will be copied to this new event form.
- [x] If the original event is from a calendar that the user does not own, the default selected calendar of the new event will be the default calendar of the current user.
- [x] If the user is not the organizer of the original event, he will become the organizer of the new event, and the organizer of the original event will be one of the attendees of the new event.
- [x] If the original event includes a video conference, the new event will also include a video conference whose link different from that of the original event, just like when adding a video conference to a brand new event.
- [x] If the original event is a recurrent exception of a recurrent series, the new event will be treated as a single normal event with the same information of the recurrent exception.
- [x] If the attendees have accepted/declined/tentatively accepted, their participation status in the new event will be reset back to when they haven't accepted/declined/tentatively accepted.
### won't do
- [ ] If the original event is a master event of a recurrent series, the new event will also be the master event of a recurrent series with the same recurrent rule.
- **reason**: duplicating a recurrent series of events is a bit complicated and time-consuming. we decided to handle this in a future issue maybe based on user feedback and the necessity to have these criteria. 
### tested on
**browser**: google chrome  86.0.4240.111 x64
**OS**: Ubuntu 18.04.4 LTS

**Comment by hantt12** [comment]
Bugs:
https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/247
https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/248
https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/250

**Comment by huy-ta** [comment]
@tanandy The feature is about to be deployed soon. Can you check the **won't do** in @rezk2ll's comment to see if it is a must-have?

**Comment by tanandy** [comment]
@huy-ta no its ok to start. when we duplicate event, we can choose if its a serie (dont replicate a serie)
