### ISSUE TITLE
[STORY] Downloading the ICS file of a calendar via a URL

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#225]
<h4 id="summary">User story summary</h4>

1. [Definition](#definition)
2. [Criteria](#criteria)
3. [Screenshots/Pictures](#screenshots)
4. [Additional notes](#notes)

<h4 id="definition">Definition</h4>

As a user, I want the URL to download the ICS file of a calendar (a.k.a the address of the calendar in iCal format).

<h4 id="criteria">Criteria</h4>

- [x] The secret address in iCal format will always allow anyone with the address to download the ICS file.
- [x] There should be an "eye" icon button that shows/hides the secret address (see [Picture 1](#picture-1)).
- [x] There should be an icon button used to copy the secret address (see [Picture 1](#picture-1)).
- [x] There should be a description below the secret address that says:

> Use this address to access the iCalendar format file (.ics).
> Warning: It allows anyone with the address to view your calendar and all of its events.

- [x] There should be a "RESET SECRET ADDRESS" button at the end to allow the owner of the calendar to get a new secret address and make the current one invalid (see [Picture 1](#picture-1)).
- [x] There should be a description above the "RESET SECRET ADDRESS" button that says:

> Use the button below to get a new secret address and make the current one invalid.

- [x] When the user clicks the "RESET SECRET ADDRESS" button, a confirmation dialog will appear with the following details (see [Picture 3](#picture-3)):

1. Title: Reset secret address?
2. Body text: Are you sure you want to make the current secret address invalid and get a new secret address?
3. Action buttons: "CANCEL" and "RESET"

- [x] The secret address should work with Google Calendar.

<h4 id="screenshots">Screenshots/Pictures</h4>

- <b id="picture-1">Picture 1</b>:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/9d06d121-0d34-4f6c-bcd5-a5c4e55f40b0)

- **Picture 2**: On mobile devices:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/65c45e4d-bfce-49dd-95a9-291a76fb2fa8)

- <b id="picture-3">Picture 3</b>: The confirmation dialog that appears when the user clicks the "RESET SECRET ADDRESS" button:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/dc98beb6-cad8-453c-be02-507070a97069)

**Comment by huy-ta** [comment]
@tanandy Check this out :wave:.

**Comment by tanandy** [comment]
tks

**Comment by tanandy** [comment]
please note that we need secret address (not optional)
(Optional) There should also be a secret address in iCal format in a calendar's configuration page, right below the public address in iCal format (1).

**Comment by huy-ta** [comment]
@tanandy @asmaNode After discussing with @renaudboyer, I have changed the criteria to only have the secret address since we do not support a truly public calendar (an external user - a person that is not an OpenPaaS user - cannot access OpenPaaS' calendars in any way).

**Comment by tanandy** [comment]
im not sure about that point, we need at least be able to share it publicly as privately

**Comment by huy-ta** [comment]
> im not sure about that point, we need at least to be able to share it publicly as privately

Yes, the secret address will do exactly that.

**Comment by tanandy** [comment]
but a user  would like also to share it without any secret (public) as google agenda do

**Comment by tanandy** [comment]
can we have a status plz ?

**Comment by rezk2ll** [comment]
> can we have a status plz ?

Soon™

**Comment by asmaNode** [comment]
This task was suspensed for more than three weeks , i will  resume working on it today

**Comment by tanandy** [comment]
thank you 👍

**Comment by tanandy** [comment]
hi thank you for your updates, what is the next step ?

**Comment by huy-ta** [comment]
> hi thank you for your updates, what is the next step ?

Now the next step is to deploy this feature.

**Comment by hantt12** [comment]
https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/381

Let's check this issue on Iphone. I will close this backlog though

**Comment by tanandy** [comment]
i reopen it since the ics file has wrong format

**Comment by rezk2ll** [comment]
follow up https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/441
