### ISSUE TITLE
Planning view should not display events from hidden calendar

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#229]
Planning view displays events from all user's calendars even if some are hidden

How to reproduce:

* Displays calendar view
* Hide a calendar
* The events are hidden in the main view but not in the planning view

![image](https://user-images.githubusercontent.com/13099240/96971754-da8b7080-1515-11eb-87df-3b0a6184ff30.png)

**Comment by rezk2ll** [comment]
# Definition of done

### what has been done
I resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/268

* [X] events from hidden calendars will not appear on the planning view
* [X] when hiding a calendar, it's related events that are already shown in the planning view should disappear.
* [X] when making a calendar visible, it's related events that are already hidden should appear in the planning view.

**demo**: https://streamable.com/1zvxzi



### environment
**browser**: google chrome  86.0.4240.183
**os**: ubuntu 18.04
