### ISSUE TITLE
Delete event on delegated calendar doesn't remove attendee events

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#236]
When a user deletes an event on delegated calendar, attendee aren't notified and attendee events aren't removed.

**How to reproduce**

* User A delegate calendar to user B
* User B create an event with attendees on User A calendar
* User B deletes the event

=> Attendees are not notified and event is present on their calendar

![image](https://user-images.githubusercontent.com/13099240/97220844-6e866200-17cc-11eb-9009-782665eb695c.png)

![image](https://user-images.githubusercontent.com/13099240/97220975-9a094c80-17cc-11eb-8c0a-015e62bf3145.png)

**Expected behavior**

Attendee should receive notification

Attendee's event must be removed

**Comment by huy-ta** [comment]
Link to the PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/259

**Comment by renaudboyer** [comment]
# Definition of Done

## Dev done

[Link to the PR](https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/259)

Fetch the calendar owner instead of the event owner before computing Event modifications


When computing event modification, Sabre Broker check who's making the modification and if it's the organizer of the event, it notifies attendees.

In case of delegation, we must fetch the calendar owner as the user act on the behalf of the calendar owner.

## Tests 

It's a backend issue so no specific Browser needed

Tested:

* the described scenario in the PR
* The delete scenario with no delegation

## Known issues

None
