### ISSUE TITLE
[i18n] inject translations

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-calendar#24]
Details [here](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Polish/i18n#code-changes-howto-solution-1-kiss)

**Comment by huy-ta** [comment]
Get the corrected translation files from this PR: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/664/diffs
