### ISSUE TITLE
Strange message when loading calendar

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#242]
When loading calendar, system shows strange message at the bottom of page and in console log
`The requested version (1) is less than the existing version (2).`

![Peek 2020-10-30 11-34](https://user-images.githubusercontent.com/53081477/97660443-2a34e380-1aa4-11eb-90e4-42a56e9e0a11.gif)

**Comment by rezk2ll** [comment]
this is the old calendar application ( backend + frontend: dev.open-paas.org/#/calendar/). @hantt12 does this behavior still appear in the calendar SPA ( dev.open-paas.org/calendar/ )?
