### ISSUE TITLE
page reloads when user clicks on Calendars tab on "Manage calendars" dialog

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#243]
Steps to reproduce:
1. In Calendar module, click on Manage calendars
2. Click on Display tab
3. Click Calendars tab

Expected result: show Calendars tab without reloading page

Actual result:
Page is reloaded

![Peek 2020-10-30 15-46](https://user-images.githubusercontent.com/53081477/97679209-8f4e0080-1ac7-11eb-8baa-c29ca395e028.gif)

**Comment by hantt12** [comment]
the same issue on tablet and mobile devices

**Comment by rezk2ll** [comment]
fixed
