### ISSUE TITLE
Duplicate event/Calendar is reset to the default one

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#247]
Steps to reproduce:

1. User A creates a calendar
2. User A creates an event on the above calendar
3. User A opens the above event
4. User A clicks on Duplicate icon
5. Check the selected calendar for the new event

Expected result:
The selected calendar should be the same as the calendar in step 2

Actual result:
The selected calendar is default calendar

![Peek 2020-11-02 12-01](https://user-images.githubusercontent.com/53081477/97831623-336fbb80-1d03-11eb-858d-78bf32d2e9e5.gif)

**Comment by rezk2ll** [comment]
this actually creates more problems than it solves.

reasons:
- `event.calendarId` is a read-only property, you can't simply set any `calendarId` you want for new events.
- when duplicating an event from another calendar *that you do not own* you need to check if the `calendarId` actually belongs to your home calendar ( that only contains your own calendars ).
- many form services will be changed.
- the current behaviour is the same as the *create a new event* behaviour, where the default calendar is selected.
- only applicable when you want to duplicate an event in the same **not default** calendar and at the same time own multiple calendars.

what do you think @huy-ta @renaudboyer ?

**Comment by huy-ta** [comment]
@rezk2ll Hi Khaled, can we just do the same thing when the user selects a calendar manually, but this time do it programmatically?
