### ISSUE TITLE
Resource manager keeps getting resource booking emails for each attendee action for an event

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#257]
# Steps to reproduce
- USER1 is a **resource manager** ( `accepts` or `declines` the requests to allocate a resource he manages )
- USER2 creates an event and invites USER3, USER4.
    - the resource manager receives an email to request a resource allocation ( let's call this a **resource email** )
![image](https://user-images.githubusercontent.com/6764881/98670679-53caf600-2353-11eb-9221-b0459ad98373.png)

- USER3 accepts the invitation:
    - the resource manager receives 2 resource emails
- USER4 declines the invitation:
    - the resource manager receives 2 resource emails

#### notes: 
*it doesn't matter if the attendee accepts or declines the event invitation.*
*it doesn't matter if the resource manager is invited/is the organizer to/of the event.*

## Resource manager INBOX after:
![image](https://user-images.githubusercontent.com/6764881/98671982-5c243080-2355-11eb-8226-dccdf7fff15d.png)

## Event organizer INBOX after:
![image](https://user-images.githubusercontent.com/6764881/98671942-4ca4e780-2355-11eb-8b80-448cf09b9186.png)

# Expected Result
1. It should return 1 Request Resource email when the user create or update the event
2. It should return 1 Response Event mail when the attendee response to the event.

# Environment
Production
openpaas-esn:1.8.1-rc8

**Comment by rezk2ll** [comment]
PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/265

**Comment by rezk2ll** [comment]
# Definition Of Done

### dev done
resolved the issue in https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/265

### ENV
OS: Ubuntu 18.04 LTS
