### ISSUE TITLE
Cannot duplicate the event in the attendee's calendar 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#258]
# Actual Result
Some recurrence events in the Attendee's Calendar cannot be duplicated when clicking the button. It shows the error log:
![image](https://user-images.githubusercontent.com/69950655/98326535-10efe200-2024-11eb-94dc-e23babd4033c.png)

![Peek 2020-11-06 11-38](https://user-images.githubusercontent.com/69950655/98326845-c327a980-2024-11eb-8ada-2e64d9166e2b.gif)

# Expected Result
It should be able to duplicate events on attendee's calendar

# Environment
Production
openpaas-esn:1.8.1-rc8

**Comment by rezk2ll** [comment]
hi, @tlle14 I can't reproduce this bug in both production and development environments.

**Comment by tlle14** [comment]
> hi, @tlle14 I can't reproduce this bug in both production and development environments.

Hi @rezk2ll,  this issue is random. Some events cannot be duplicated and return the error log. We should continue to find a way to reproduce.
