### ISSUE TITLE
Duplicate event in Planning View

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#269]
Steps to reproduce:
1. Toggle off the calendar from the left menu
2. Open the planning view
3. Toggle on the calendar from the left menu
4. Check number of event shown on planning view

Expected result:
List/number of events in the newly toggled on calendar should be correct

Actual result:
Duplicated event

![Peek 2020-11-20 10-24](https://user-images.githubusercontent.com/53081477/99754516-1caad080-2b1b-11eb-8cf8-2152922855ea.gif)

**Comment by tlle14** [comment]
Thank @rezk2ll  and @huy-ta 
Retest pass!
![Peek 2020-12-02 10-48](https://user-images.githubusercontent.com/69950655/100825996-f88caf00-348b-11eb-826b-1363a94add37.gif)
