### ISSUE TITLE
Recurrent events do not work well with daylight saving time

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#272]
#### Steps to reproduce

- As User B:

1. Log in 
2. Change the timezone to Europe/Paris (UTC+01)
3. Go to Calendar
4. Create a recurrent event with the first occurence happening before November 1, 2020 (before DST ends in 2020), invite User A.

#### Expected behaviour

The events in User A's calendar have correct date & time.

#### Current behaviour

The events in User A's calendar are 1 hour earlier than the events in User B's calendar.

**Comment by renaudboyer** [comment]
Attendee event of a recurring event are stored in UTC (Z) instead even if the organizer has created the event with timezone'd dates.

It should be related to Sabre scheduling process

**Comment by huy-ta** [comment]
I can't seem to reproduce this in my local, but it still persists on https://dev.open-paas.org.
