### ISSUE TITLE
Event alarm is lost when dragging & dropping an event

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#273]
#### Steps to reproduce

1. Create an event with an alarm
2. Update the event's date & time by dragging & dropping it in the Calendar main view.

#### Expected behaviour

The alarm should still be the same as before.

#### Current behaviour

The alarm is lost.

**Comment by rezk2ll** [comment]
# Definition of Done

### What I've done
- I've fixed the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/277

- demo: https://streamable.com/rc36nn

### Environment
**OS**: Ubuntu `18.04 LTS`
**Browser**: chrome `87.0.4280.66`

**Comment by tlle14** [comment]
Thank @rezk2ll 
Retest pass
![Peek 2020-12-02 10-52](https://user-images.githubusercontent.com/69950655/100827491-6edee080-348f-11eb-8331-1f130231b162.gif)
