### ISSUE TITLE
Importing same events in different user calendars result in multiple occurences of the same events

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#276]
Import feature allows creating multiple version of the same event in different user calendars.

#### How to reproduce

* Create an ICS file containing one event with User A as organizer (using User A email) and User B as attendee
* User A should have 2 calendars, default and a extra one.
* Import ICS in the default calendar
* Import ICS in the extra calendar

#### Current behaviour

=> The event will appear in both calendar
=> As both event have the same UID, updating any duplicate will notify attendees.

NOTE: If User A import the ICS multiple times in the SAME calendar, then event is not duplicated.

Demo:

https://streamable.com/m0rhg8

NOTE: In the demo, we observe also issue #275 .

![image](https://user-images.githubusercontent.com/13099240/99978432-3b70c780-2da6-11eb-825e-1e85003155f3.png)

#### Expected behaviour

As discussed, when importing the same events in different user calendars, the events that are imported later will replace the previous events. And when importing the same events in a different calendar, the previously imported events in another calendar will be updated & moved to the new calendar.

**Comment by huy-ta** [comment]
I have updated the issue to add the expected behaviour that we discussed the other day.

**Comment by rezk2ll** [comment]
PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/279
