### ISSUE TITLE
Cannot export the calendar

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#290]
# Actual result
Cannot export the calendar. It redirects to the error page
![Peek 2020-11-27 14-19](https://user-images.githubusercontent.com/69950655/100421873-cf4ed600-30bb-11eb-9822-95f23988f00f.gif)

# Expected Result
Able to export the calendar

# Environment
DEV platform

**Comment by rezk2ll** [comment]
# Definition of Done

### what i did
i fixed the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/293
### env
browser: chrome `87.0.4280.66`

**Comment by rezk2ll** [comment]
# Definition of Done

### what i did
i resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/303
### env
OS: Ubuntu `18.04 LTS`
browser: chrome `87.0.4280.66`

**Comment by tlle14** [comment]
Thanks @rezk2ll 
Retest pass!
![Peek 2020-12-02 10-17](https://user-images.githubusercontent.com/69950655/100824199-4ef7ee80-3488-11eb-8b75-606718d609af.gif)
