### ISSUE TITLE
Some special character has been encoded in the notification message

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#294]
# Actual Result
Some special characters such as `&` and `< >` are encoded in the messages 
![image](https://user-images.githubusercontent.com/69950655/100427010-5dc75580-30c4-11eb-9ff2-de65ded81412.png)

# Expected Result
Special characters should be displayed normally in the message

# Environment
DEV platform

**Comment by rezk2ll** [comment]
# Definition of Done

### dev done
i resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/333
**demo**: https://streamable.com/shg1rr

### Environment
OS: Ubuntu ` 18.04 ` TLS
browser: chrome `87.0.4280.66`
