### ISSUE TITLE
Mobile iOS > UI > In the event details, Copy Link button name is hidden 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#296]
# Precondition
The event has a video conference

# Actual Result
The button `copy link` in the event details is partially hidden. 
![image](https://user-images.githubusercontent.com/69950655/100439502-37121a80-30d6-11eb-881c-11855d2493a9.png)

# Expected result
The button should display its name fully

# Environment
DEV platform
iPhone 11 Pro Max - Safari

**Comment by huy-ta** [comment]
Duplicate of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/152.
