### ISSUE TITLE
Cannot duplicate alarm when duplicate an event

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#297]
# Precondition
The event has an alarm

# Actual Result
When duplicating an event, the alarm was displaying in the form but isn't created in the duplicated event
![Peek 2020-11-27 17-51](https://user-images.githubusercontent.com/69950655/100441571-48105b00-30d9-11eb-90e9-ad35587e4721.gif)

# Expected Result
The alarm should be duplicated

# Environment
DEV platform

**Comment by rezk2ll** [comment]
# Definition of Done

### dev done
resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/354

### env
OS: `Ubuntu 18.04 LTS`
browser: `chrome 87.0.4280.141`
