### ISSUE TITLE
UI > Event that tentatively accept displays in bad UI

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#298]
# Precondition
User response to the event with `Maybe`

# Actual Result
The event has (?) icon has time and event name not in the same line
![image](https://user-images.githubusercontent.com/69950655/100443958-392ba780-30dd-11eb-9840-c28d1ccbcec5.png)

# Expected Result
The event has (?) icon should display its time and name in the same line.

# Environment
DEV platform
Desktop - Chrome, Firefox

**Comment by huy-ta** [comment]
Cannot be reproduce anymore.

![image](https://user-images.githubusercontent.com/24670327/110887409-d9b87700-831c-11eb-842d-c541d7229410.png)
