### ISSUE TITLE
Bad email template when propose a new time for the event 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#299]
# Actual Result
Email template has a bad UI
![image](https://user-images.githubusercontent.com/69950655/100568303-73738f80-32fd-11eb-80f1-4c09b6b92e18.png)

# Expected Result
- The email content should be resized.
- The proposed time should be emphasized

# Environment
DEV platform
Desktop

**Comment by huy-ta** [comment]
This will be fixed via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/234.
