### ISSUE TITLE
Mobile > Bad UI for displaying calendar emails 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#300]
# Actual Result
Calendar email has a bad UI on mobile
![1606712287490](https://user-images.githubusercontent.com/69950655/100570508-80937d00-3303-11eb-8e75-7c082c7d33b6.JPEG)

# Expected Result
Calendar email should be responsive

# Environment
DEV platform
- Android: Samsung A51, Chrome
- iOS: iPhone 11 Promax, Safari

**Comment by huy-ta** [comment]
This will be fixed via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/234.
