### ISSUE TITLE
Mobile > In shared calendar, the recurrence event is duplicated when Owner change its privacy

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#302]
# Precondition
UserA shares a calendar with "Edit" permission
UserB gets the calendar of userA

# Actual Result
When userA changes privacy (from public -> private)  of a recurrence event in the sharing calendar, userB will see that the event is duplicated on his phone. He needs to refresh the page to see it becomes normal.
![1606738083659](https://user-images.githubusercontent.com/69950655/100608738-6e373480-333f-11eb-8b9d-f52401f2d8bd.JPEG)

# Expected Result
The calendar of UserB should be updated correctly, no need to refresh the page

# Environment
DEV platform
Android: Samsung A51, Chrome

**Comment by huy-ta** [comment]
I cannot reproduce this issue anymore.
