### ISSUE TITLE
The default calendar isn't selected automatically when duplicating an event in the delegated calendar

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#307]
# Precondition
UserA delegates a calendar to userB with "see all events" permission

# Actual Result
When userB duplicates an event in the delegated calendar, the calendar is empty in the form "create new event"
![image](https://user-images.githubusercontent.com/69950655/100712857-05ef5e00-33e6-11eb-8cdb-50f99ea8fe20.png)

# Expected Result
If the original event is from a calendar that the user does not own, the default selected calendar of the new event will be the default calendar of the current user.
As per https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/222

# Environment
DEV platform

**Comment by rezk2ll** [comment]
# Definition of Done

### dev done
resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/324

### env
OS: `Ubuntu 18.04 LTS`
browser: `chrome 87.0.4280.141`
