### ISSUE TITLE
[STORY] Delete an event as an attendee

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#309]
#### User story summary

- [Definition](#definition)
- [Criteria](#criteria)
- [Notes](#notes)

<h4 id="definition">Definition</h4>

As a user, I want to be able to delete an event in which I am an attendee.

- **Given** that I am an OpenPaaS user
- **When** I am invited to an event
- **Then** I open the event
- **Then** I press the "Delete" button to delete the event

<h4 id="criteria">Criteria</h4>

- [x] The deleted event will no longer appear in my calendar.
- [x] Every other attendee (including the organizer) will see my participation status for the event as "Declined".
- [x] I will no longer receive any notifications or alarms about the event.
- [x] When the organizer updates the event with [significant changes](#sig), the event will reappear in my calendar. I will continue to receive notifications and alarms about the event.

<h4 id="notes">Notes</h4>

- <em id="sig">Significant changes</em> are changes to these fields (see https://tools.ietf.org/html/rfc5546#page-11):
  - Start date & time
  - End date & time
  - Recurrent rule (if it's a recurrent event)
  - Exception dates (if it's a recurrent event)
  - Status

**Comment by rezk2ll** [comment]
# Definition of Done

### Dev Done
resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/311

**demo**: https://streamable.com/ifqouf

### Environment tested
Desktop: Ubuntu `18.04 LTS`
browser: google chrome `87.0.4280.66`

### New bugs
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/335 https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/331

**Comment by hantt12** [comment]
One issue https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/387
