### ISSUE TITLE
create new calendar with special character, notification create success didn't display calendar name correct

### ISSUE THREAD

**Issue by Trongk58d** [OpenPaaS-Suite/esn-frontend-calendar#318]
create new calendar with name have special characte like:  `<AT>` New Calendar

![image](https://user-images.githubusercontent.com/69950669/101310317-27869480-3881-11eb-8330-24102e7ddd2e.png)

after click on button "CREATE", a notification will display with format "`<AT>` New Calendar has been created" should display but, calendar name display wrong (`&lt;`AT`&gt;` New Calendar has been created)

![image](https://user-images.githubusercontent.com/69950669/101310470-8ba95880-3881-11eb-93b6-60c00c3828e6.png)

**Comment by rezk2ll** [comment]
this has been already fixed
