### ISSUE TITLE
When user shares a calendar, I should not be able to modify fields on event user is attending

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#319]
How to reproduce

* Log with user A
* Shares User A's main calendar to user B with Edit permissions
* Log with User B
* Create an event with user B with user A as attendee
* Click on event user A is attending
* Attendees and Resources field are accessible

![image](https://user-images.githubusercontent.com/13099240/101471962-41d77580-3948-11eb-9797-ed63a1b027c0.png)

Expected behavior

Event form display should be the same as if I was logged with User A 

* Attendees and Resources field should be hidden

![image](https://user-images.githubusercontent.com/13099240/101472229-9aa70e00-3948-11eb-9404-3d738d0d2e2d.png)

**Comment by asmaNode** [comment]
@renaudboyer please check this senario https://streamable.com/f48std
The senario that you are described is in the case when the user B create an event with a different calendar (not the delegated one)
