### ISSUE TITLE
Fix the incorrect notification sent to the organizer when an attendee deletes an event

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-calendar#331]
see https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/311#issuecomment-740423607

**steps to reproduce**:
- delete an event that you are an attendee within 

**Expected behaviour**: 
An email should be sent to the organizer with its title beginning with "Declined..."

**Current behaviour:**
An email is sent to the organizer with its title beginning with "Participation updated..."

**Comment by huy-ta** [comment]
This has been fixed by https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/261.
