### ISSUE TITLE
Location field does not support http link in notification emails

### ISSUE THREAD

**Issue by asmaNode** [OpenPaaS-Suite/esn-frontend-calendar#339]
**Reproduce the bug** 
*Create an event
*Put jitsi link in location field

The attendee users receive an invitation with simple text  no clickable
![location](https://user-images.githubusercontent.com/43316837/102769542-18284080-4383-11eb-986a-ef9c6e890b39.png)

**Expected behaviour :** 
The field location must support http links and show it in details event

**Comment by asmaNode** [comment]
https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/702

**Comment by hantt12** [comment]
Hi all, please also check in event reminder email (alarm) 

![2021-01-19_17-51](https://user-images.githubusercontent.com/53081477/105024791-17b4bf80-5a7f-11eb-976b-868b6050211b.png)
