### ISSUE TITLE
Boostrap Datepicker translation  

### ISSUE THREAD

**Issue by asmaNode** [OpenPaaS-Suite/esn-frontend-calendar#346]
Actual: Date picker displays days in a week in English
Expected: Should display in the corresponding languages

https://user-images.githubusercontent.com/69950655/90869205-1a24c780-e3c2-11ea-9084-9ba0a892e62f.png
https://user-images.githubusercontent.com/69950655/91022623-ab44aa00-e61f-11ea-9596-b255f3b0a84e.png

**Comment by asmaNode** [comment]
Demo for the current solution : 

https://user-images.githubusercontent.com/43316837/104700787-fb2e2580-5714-11eb-9ffe-4d3a487f57fd.mp4

**Comment by asmaNode** [comment]
related PR : https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/164

**Comment by huy-ta** [comment]
Closed in favour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/346.
