### ISSUE TITLE
Translate video conference description  in event details (email invitation)

### ISSUE THREAD

**Issue by asmaNode** [OpenPaaS-Suite/esn-frontend-calendar#347]
Actual: Open the event details, the note for video conference is in English
Expected: It should be translated into the user's selected language
https://user-images.githubusercontent.com/69950655/91031638-15168100-e62b-11ea-96f1-0914deb4a320.png

**Comment by asmaNode** [comment]
https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.videoconference.calendar/merge_requests/6

**Comment by hantt12** [comment]
Open discussion: if user changes the account's language after the event is created, which language should be shown in the note? 
Currently it's the old language

**Comment by huy-ta** [comment]
> Open discussion: if user changes the account's language after the event is created, which language should be shown in the note?
> Currently it's the old language

@hantt12 @asmaNode The expected behaviour should be to always show the note according to the current language.
