### ISSUE TITLE
[STORY] Event form collapsibility

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#348]
#### User story summary

- [Related epic](#related-epic)
- [Definition](#definition)
- [Criteria](#criteria)
- [Design](#design)

<h4 id="related-epic">Related epic</h4>

[Improving the event form](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/373)

<h4 id="definition">Definition</h4>

As a user, I want to a simple event form with just the basic fields by default when I create, update, or view an event.

- **Given** that I am an OpenPaaS user
- **When** I am in Calendar
- **Then** I open an event to create, update or view it

<h4 id="criteria">Criteria</h4>

- [ ] By default, when opening the event form, only the basic fields should be displayed (see [Picture 1](#picture-1)).
- [ ] When clicking the "MORE OPTIONS" button (see [Picture 1](#picture-1)), all the fields will be displayed.
- [ ] When clicking the "FEWER OPTIONS" button (see [Picture 2](#picture-2)), only the basic fields will be displayed.

<h4 id="design">Design</h4>

- <b id="picture-1">Picture 1</b>: The event form when creating an event with only the basic fields:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/2647c8f7-dcd7-4831-a286-fbc7232029a9)

- <b id="picture-2">Picture 2</b>: The event form when creating an event with all the fields:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/98b5cf0e-e9eb-4ff9-97d8-1018d909b859)

**Comment by huy-ta** [comment]
![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/a70c7317-3954-495a-837e-bcf6d2b8497b)

**Comment by hantt12** [comment]
Issue on mobile browser https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/487

**Comment by hantt12** [comment]
still occurs in Iphone 11 and iphone XR
