### ISSUE TITLE
Provide a button to refresh the calendar without refreshing the whole page 

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#352]
#### Current behaviour

When there's something that goes wrong right after the user executes an action, the Calendar app will display a notification message with something like "Please refresh your calendar". The user is then forced to do a full page reload (F5).

#### Suggested behaviour

We should also provide a "REFRESH CALENDAR" button which the user can click to manually refresh just the calendar (re-fetching all the events), not the whole page.

**Comment by huy-ta** [comment]
## Definition of Done

#### What I have done

I have added a button that allows a user to refresh his/her calendar manually without having to refresh the whole page via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/360.

![image](https://user-images.githubusercontent.com/24670327/104168174-3805ce00-5430-11eb-8faa-54482f9f3ad1.png)

**Comment by hantt12** [comment]
Minor UI issue at https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/382
