### ISSUE TITLE
[Sabre] Pick a JWT decoding library

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-calendar#369]
suggestions:

* [x] https://github.com/firebase/php-jwt
* [ ] https://auth0.com/docs/libraries/auth0-php/validating-jwts-with-auth0-php

**Comment by huy-ta** [comment]
https://github.com/firebase/php-jwt looks good to me.

There's also https://github.com/lcobucci/jwt which is what `auth0-php` is using under the hood I guess.

**Comment by renaudboyer** [comment]
The firebase one looks good to me too
