### ISSUE TITLE
Event search is broken in some cases

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#374]
Due to [this fix](https://ci.linagora.com/linagora/lgs/openpaas/sabre-vobject/merge_requests/17), the event search feature is now broken in some cases. For details, please test and check this list of test cases:

https://cryptpad.fr/sheet/#/3/sheet/edit/0842aa509541ba361b00635c7ac7d6e6/

**Comment by huy-ta** [comment]
This will be solved by https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/261.

**Comment by rezk2ll** [comment]
is it resolved?

**Comment by huy-ta** [comment]
This has been resolved by https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/261.
