### ISSUE TITLE
Issues in Downloading the ICS file in iphone

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#381]
2 issues:

- When user clicks in Copy button, "Link copied to clipboard" message is not shown
- When external user access the link, file is not downloaded

See video below:

https://user-images.githubusercontent.com/53081477/105145777-c6b1d380-5b31-11eb-83d3-f04a2d40772c.mp4

**Comment by huy-ta** [comment]
Cannot be reproduced anymore as of 1.9.0-rc8.
