### ISSUE TITLE
Sometimes attendee fails to delete event

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#386]
Given that I am an OpenPaaS user
When I am invited to an event
Then I open the event
Then I press the "Delete" button to delete the event

This does not always happen but when I try for 5-6 times, it happens twice then it derserves an investigation

![2021-01-21_10-18](https://user-images.githubusercontent.com/53081477/105275572-3ecfd600-5bd2-11eb-892c-c21158a52469.png)

**Comment by huy-ta** [comment]
I cannot reproduce the issue anymore.
