### ISSUE TITLE
Attendee is able to update the event

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#388]
1. User A shares his default calendar to User B with Edit permission (Delegation)
2. User A creates an event in his default calendar with user B as attendee
3. Log in as user B to view user B's default calendar (NOT the shared calendar)
4.  Update date time of the event above by dragging and dropping

Expected result:
User B is not able to update the event as he is attendee

Actual result:
User B is able to update

![Peek 2021-01-21 10-39](https://user-images.githubusercontent.com/53081477/105276985-1c8b8780-5bd5-11eb-89ba-2af7c8b049f7.gif)

**Comment by asmaNode** [comment]
@hantt12  The current behaviour is expected ; please check the video with whole senario : 

- UserA in the right of screen will delegate his calendar to userB in the left of screen with edit permissions

- User B can not update the  event in his calendar ( the event box is disabled) but he can update the event of main calendar

**Which is strange in your screen why there is no a duplicated event .Can you explain more what you had done please  :)**

https://images.zenhubusercontent.com/276895569/25a7e8e0-8cd5-4eb4-9afe-18310425756d/delegateandupdateevent.mp4

**Comment by huy-ta** [comment]
@asmaNode I think Ha overcomplicated the steps to reproduce the bug.

Here's the simplified steps to reproduce the bug:

- As User A, create a daily event and invite User B.
- As User B, try dragging & dropping the recurrent event.

See if you can reproduce the bug with the above steps.

**Comment by asmaNode** [comment]
@huy-ta  you miss the step of delegation ?

**Comment by huy-ta** [comment]
@asmaNode The delegation stuff is not required to reproduce the bug.

**Comment by asmaNode** [comment]
@huy-ta no i can't reproduce the bug , if userb is just an attendee the recurrent event will be disabled in its calendar so he cant drap and drop , forthat i said there must be  a delegation issue in ha's bug

**Comment by huy-ta** [comment]
@asmaNode That's strange. I can reproduce the bug by following the 2 steps above every single time:

https://images.zenhubusercontent.com/276895569/44800f8a-87c5-45b6-b1fe-6200989c0535/update_event_as_attendee_bug.mp4
