### ISSUE TITLE
Deleted event re-appears in attendee's calendar when organizer saves the event without any changes

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#390]
1. User A creates an event with user B as attendee (either repeated event or single event)
2. User B deletes the event from his calendar
3. User A opens the event and saves without changing anything
4. User B check the calendar

Expected result:
User B does not see the event

Actual result:
User B see  the event as declined

**Comment by asmaNode** [comment]
it not a bug , it is the expected behaviour
