### ISSUE TITLE
Mobile/(+) button is overlapped in Calendar Configuration screen 

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#391]
![IMG_3531](https://user-images.githubusercontent.com/53081477/105279008-4181f980-5bd9-11eb-987a-e754d6fbf152.PNG)

**Comment by asmaNode** [comment]
@hantt12 can you put the type of device plz

**Comment by rezk2ll** [comment]
> @hantt12 can you put the type of device plz

iPhone

**Comment by asmaNode** [comment]
yes , i know but wich one ? it is working for me

**Comment by hantt12** [comment]
Hi @asmaNode tested today in dev platform using my iphone 11. Safari. iOs 14.4
![153453914_490851372072538_8597173239224977065_n](https://user-images.githubusercontent.com/53081477/108851418-fc594900-7616-11eb-9714-7c28db12cf59.jpg)
