### ISSUE TITLE
Mobile/Safari - unexpected margin on both left & right sides when viewing in landscape 

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#397]
![IMG_3533](https://user-images.githubusercontent.com/53081477/105315150-7c902700-5bf1-11eb-99d8-3596b83c3b14.PNG)

**Comment by huy-ta** [comment]
This is a feature of some iPhones that have a notch. Apple doesn't want content to be covered by it, so the width of the page in landscape mode is automatically shortened a little bit to avoid the notch.

P/s: For anyone that wants to try to force the content to cover the notch also, you can try:

```
<meta name="viewport" content="width=device-width, initial-scale=1, **viewport-fit=cover**">
```
