### ISSUE TITLE
Can't open recurrence exceptions after searching for events

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#404]
#### Steps to reproduce

- Go to Calendar
- Create a recurrent event
- Create a recurrence exception
- Search for the recurrence exception
- Open the recurrence exception in the search result

#### Current behaviour

Nothing happens when trying opening the recurrence exception in the search result.

#### Expected behaviour

The event dialog displaying the details about the event should appear.

**Comment by asmaNode** [comment]
can not reproduce the bug

https://user-images.githubusercontent.com/43316837/107756747-f5802b80-6d24-11eb-841a-9955d079690b.mp4

**Comment by huy-ta** [comment]
I can't reproduce it anymore either.
