### ISSUE TITLE
Issues with location open link button

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#406]
Location open link button has 2 issues:

* [x] Link detection check edited content but not open the edited link the saved one (with some glitches)
* [x] If a link a detected but have no protocol, we should add `http://` protocol

**Comment by asmaNode** [comment]
**demo:**
https://user-images.githubusercontent.com/43316837/105866529-6076f600-5ff4-11eb-8556-8da8f0f284c7.mp4
