### ISSUE TITLE
Attendee email address is not autopopulated into recipient field when user clicks on "Mail to attendee" option

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#418]
Steps:
- Create an event with attendees
- Open the event
- Click on Mail to attendee

Expected result:
Attendee email addresses are auto-populated to Recipient field

Actual result:
It's not populated

![Peek 2021-02-22 15-47.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/3b146f77-bf30-4eac-a7a2-adaa6f9cbff9)

**Comment by asmaNode** [comment]
PR :https://github.com/OpenPaaS-Suite/esn-frontend-mailto/pull/65
