### ISSUE TITLE
Bad behavior of event 'More options' button

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-calendar#421]
When opening an event and clicking on this button:

<img width="267" alt="Capture d’écran 2021-02-23 à 15 13 24" src="https://user-images.githubusercontent.com/264403/108856003-e2554180-75e9-11eb-841e-97cc7feeb0af.png">

I expect something to happen without any other interaction. In the current case, the modal should grow, or scroll, or anything else.

**Comment by huy-ta** [comment]
@chamerling I'm not sure what you mean here. The event dialog does grow when you press the "MORE OPTIONS" button:


https://user-images.githubusercontent.com/24670327/110886181-d3290000-831a-11eb-81e5-ff3d292bde3e.mp4

**Comment by chamerling** [comment]
OK it looks OK on dev, was not OK on prod
