### ISSUE TITLE
The calAttendeeAvatarExternal component loads image from server

### ISSUE THREAD

**Issue by piavgh** [OpenPaaS-Suite/esn-frontend-calendar#44]
Module `esn-frontend-calendar-public` will be broken because it also uses this component

The avatar is missing (it should appear next to the green check mark)
![Screenshot 2020-08-11 14:09:30](https://user-images.githubusercontent.com/4060207/89868204-9eb26180-dbdc-11ea-80f6-f33122009bf3.png)

Related file: `src/esn.calendar.libs/app/components/avatar/attendee-avatar/external/attendee-avatar-external.pug`

```javascript
.cal-attendee-avatar
  a.avatar(href="", ng-attr-title='{{::ctrl.getDisplayName()}}')
    img(ng-src="{{ctrl.avatarUrl}}", src='/images/throbber-amber.svg', fallback-src='/images/user.png', alt="{{ 'Avatar' | translate }}")
```

**Comment by huy-ta** [comment]
This is currently the expected behaviour. All the avatar images will be fetched from the backend server, so if you run an SPA without the backend server, it will break.
