### ISSUE TITLE
Attendee does not receive invitation email if he is added after the event is created

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#460]
Steps:
1. User A creates an event and SAVE
2. User A opens the above event again
3. Add user B to the above event and SAVE
4. User B check inbox

Expected result:
User B receives invitation email

Actual result:
User B does not receive invitation email

**Comment by huy-ta** [comment]
Still reproducible as of 1.9.0-rc8.
