### ISSUE TITLE
Remove old calendar inbox objects

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#462]
#### User story summary

1. [Definition](#definition)
2. [Issue](#issue)
3. [Solution](#solution)
4. [Criteria](#criteria)

<h4 id="definition">Definition</h4>

CalDAV standard offers an inbox feature for a user.

Each time an event is modified by the organizer, the modified event is send to 
Inbox stores each modification that have been done to an user event.

<h4 id="issue">Issue</h4>

The Inbox acknowledge/cleaning should be done by DAV client using this feature.
In case the user doesn't use this feature, the Inbox will grows for ever.

<h4 id="solution">Solution</h4>

Sabre should remove automatically old inbox messages to avoid database overcrowding.

<h4 id="criteria">Criteria</h4>

We'll use a Mongo TTL index to remove old messages

* [ ] Create a `timestamp` field in `schedulingobjects` collection
* [ ] Create a TTL index on `timestamp` field in `schedulingobjects` collection
* [ ] Script the database update: Update the `timestamp` fields to 2 months ago

NOTE: TTL time should be 2 months.

**Comment by huy-ta** [comment]
Here's the PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/300
