### ISSUE TITLE
[GROOMING] Choose a way to listen MQ for Sabre plateform

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#471]
ITip messages from mail server are sent through RabbitMQ topic.

We need to choose a way to listen RabbitMQ topic and process the ITip messages

###### Hints

* Php process that polls RabbitMQ endlessly
* Php process that polls RabbitMQ launched by cron
* Use another technology (that doesn't use polling)
* We can send an ITIP HTTP request to launch the processing

[[STORY] Handle ITIP messages from mailing server](https://app.zenhub.com/workspace/o/openpaas-suite/esn-frontend-calendar/issues/464)

**Comment by huy-ta** [comment]
So to sum up about this:

#### About PHP & RabbitMQ

PHP does have some libraries that use RabbitMQ's [`basic.consume`](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.consume), which allows the broker to push messages to clients. The two most notable libraries are: [php-amqplib](https://github.com/php-amqplib/php-amqplib) and [BunnyPHP](https://github.com/jakubkulhan/bunny). However, there are some limitations:

- By nature, the PHP process that waits for the messages will run indefinitely, blocking everything else in that same process.
- That PHP process will handle the messages from the queue synchronously. Therefore, if there are multiple messages that come at the same time, they will have to be handled one by one, synchronously (unless we spawn multiple PHP processes that subscribe to the same queue).

#### About our Calendar solution

Maybe we need to think of our Calendar solution as not just Sabre (PHP). PHP processes are quite limited for a full-fledged Calendar application. We can introduce other technologies to the whole stack (e.g. NodeJS), and call this stack **TCalendar**. Our stack will no longer be just about Sabre anymore, and we'll be much more free.

**Comment by huy-ta** [comment]
I think we can resort to using NodeJS for RabbitMQ & real-time communications in our Calendar stack. What do you think? cc @renaudboyer @rezk2ll @asmaNode @thebtililya

**Comment by rezk2ll** [comment]
i agree with you

**Comment by renaudboyer** [comment]
I agree with the no Php policy.

NodeJs should be choosen but I'd like to check with DevOps to confirm that.

**Comment by renaudboyer** [comment]
Few Php libraries dealing with Async:

* [Amp](https://amphp.org/)
* [WebSocketBundle](https://github.com/GeniusesOfSymfony/WebSocketBundle)
* [ReactPhp](https://reactphp.org/)
* [Swoole](https://www.swoole.co.uk/)
