### ISSUE TITLE
[TASK] Move ITip code from JSON plugin to a new ITip Plugin

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#481]
Create an Itip plugin that will contains the Itip feature.

For now, code is in JSON Plugin and should be moved to this new plugin

Criteria

* [ ] Create a ITipPlugin in ESN\CalDAV\Schedule namespace
* [ ] Move Itip code from JSON plugin
* [ ] Refactor tests

**Comment by huy-ta** [comment]
PR: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/297
