### ISSUE TITLE
Event time in emails should be consistent

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#483]
Currently time in Reminder email is different from other event related emails
Please make it consistent and use user timezone

![2021-03-24_10-10.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/08144ed0-7c21-4ed7-ac00-7d59432bc5b1)
![2021-03-24_10-09.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a652fd6f-0c99-43f6-98f0-faf618c30a59)

**Comment by huy-ta** [comment]
This is fixed via PR: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/723.
