### ISSUE TITLE
Incorrect name of user accepting/declining/replying "Maybe" the event invitation

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#484]
Steps to reproduce:
1. User A invites User B to an event
2. User B accepts the event invitation
3. User A checks acceptance email

Expected result:
Email should show that User B accepts the event Invitation

Current behavior:
Email shows that User A (organizer) accepts the event invitation

![2021-03-24_10-27.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/1b5b849f-2d5b-457b-b79b-a2e11e442e08)

**Comment by huy-ta** [comment]
This is fixed via PR: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/722.
