### ISSUE TITLE
Unable to change the date of the event while creating the event

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#485]
Steps:
1. Go to Calendar
2. Open Create new event form
3. Change the start date/end date 
4. Save the event
5. Check the date of the newly created event

Expected result:
Date = selected in step 3

Current behavior:
Date = default date
![Peek 2021-03-24 10-34.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/eb0178c0-6c15-4ec1-bdf3-e1fa43bb1b72)

**Comment by huy-ta** [comment]
The issue has been fixed with https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/482.
