### ISSUE TITLE
Unable to respond to event invitation from links in the emails

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#486]
Steps:
User A invites User B to an event
User B opens the invitation email
Click Yes/No/Maybe in the invitation email

Expected result:
Accept/Decline/Tentative successfully

Actual result:
Failed

![Peek 2021-03-24 10-37.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/add360ac-e6b5-4771-95ec-8714fdc48b13)

**Comment by huy-ta** [comment]
The issue has been fixed via https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/303.
