### ISSUE TITLE
some last fields of Create Event/Update Event form are not shown fully in mobile browser

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#487]
Fields can't be seen fully => user cannot input value
See Screenshots
![IMG_0123.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/4ab0a149-4dfe-42f5-9452-ed02c3d87f99)
![IMG_0122.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/b1d00862-b20d-4076-92ef-be4a47dbc45a)

**Comment by huy-ta** [comment]
@hantt12 Actually this is an issue that only exists in iOS devices.
