### ISSUE TITLE
Event view popover avatars are not correct

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-calendar#507]
should use the user selected avatar

![image](https://user-images.githubusercontent.com/6764881/113576976-6d2d5100-9618-11eb-8cfd-5452a6411173.png)

**Comment by tlle14** [comment]
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/73402586-82a3-4e00-861a-f6a7c0169c3e)
