### ISSUE TITLE
event invitation email check mark is not a check in mobile 

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-calendar#518]
Client: Gmail 

![IMG_20210408_011738.jpg](https://user-images.githubusercontent.com/6764881/113989921-d2678900-9848-11eb-9315-d6c16e2b1b20.jpg)

**Comment by renaudboyer** [comment]
We may see if it's fixable

**Comment by huy-ta** [comment]
## DoD

#### What I have done

I've fixed the issue via https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/728.

#### Environments tested

- Gmail client in Android 10.
- Default email client in Android 10.
