### ISSUE TITLE
ICS secret address gets changed/reset unexpectedly

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#519]
#### Steps to reproduce

1. As User A, get the secret address of the default calendar.
2. As User B, get the secret address of the a calendar.
3. As User A, get the secret address of the default calendar.

#### Current behaviour

The secret address of the default calendar of User A is changed compared to the first time.

#### Expected behaviour

The secret address of the default calendar of User A should not be changed.

**Comment by tanandy** [comment]
yes thats pretty annoying, thank you !

**Comment by tanandy** [comment]
do you reproduce it @asmaNode ?

**Comment by asmaNode** [comment]
no i didnt , the link that i had generated from yesterday is working now , but i still test @tanandy

**Comment by tanandy** [comment]
Hi @chamerling . Any token rotation ? Or im the only one

**Comment by tanandy** [comment]
Its the private link btw with a token

**Comment by chamerling** [comment]
I do not use it for now but I will.
This is a pretty annoying 🐛

**Comment by asmaNode** [comment]
related PR
https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1342/commits

**Comment by asmaNode** [comment]
@tanandy  the issue that you have is just with google calendar ?

**Comment by tanandy** [comment]
i only tested on gcalendar

**Comment by chamerling** [comment]
I commented https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1342/diffs#note_355795. You must not set all the tokens to expiresAt = 0. You must have it never expires in your case, that's all!

**Comment by asmaNode** [comment]
Updated ! i just create a separate function in our case with long lived token

**Comment by huy-ta** [comment]
JWT will make the link much longer than Google can accept, so it is a no-go here. And I don't think switching to JWT will fix the current issue.

The current issue is, in production, somehow a new link gets generated after a period of time (for now we suppose that it's one day). We need to investigate why that is so because the link is supposed to be genereted again _only when_ clicking the "RESET SECRET ADDRESS" button.

By the way I cannot reproduce the bug locally, so it might have something to do with the production environment:

> 19/4: localhost, admin@open-paas.org, My agenda
> http://localhost:8080/calendar/api/calendars/5f60334e78d1b021351f9f6e/5f60334e78d1b021351f9f6e/calendar.ics?token=a1466CeGdfJG2Fk43sLqCF

> 20/4: localhost, admin@open-paas.org, My agenda
> http://localhost:8080/calendar/api/calendars/5f60334e78d1b021351f9f6e/5f60334e78d1b021351f9f6e/calendar.ics?token=a1466CeGdfJG2Fk43sLqCF

**Comment by huy-ta** [comment]
Here's the fix: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/729.

**Comment by tanandy** [comment]
can you explain what was the root cause ?

**Comment by huy-ta** [comment]
@tanandy The issue was in our code. There was a missing function argument which causes the secret address to be saved in the domain settings, not the user settings. So when there's another user getting a secret address, it overrides the existing domain settings, thus the issue.

**Comment by tanandy** [comment]
ok i got it, but i dont understand why when another user change its own secret link, it impacts myself.
Do we lack some isolation ?

**Comment by huy-ta** [comment]
@tanandy Everyone was using the domain settings which were shared across all users.

**Comment by tanandy** [comment]
alright, but it seems really easy to forget to add the 'true' parameter. Any way to prevent this to happen again ?

**Comment by huy-ta** [comment]
@tanandy True. It is pretty confusing. The function is named `forUser`, which is supposed to be **for user**.

Unfortunately, I don't think there's a way to fix this. We can change the way the `forUser` function works, but it will require a lot of code changes in the codebase (which is nearly impossible atm).

**Comment by chamerling** [comment]
😳 Thx for the fix

**Comment by hantt12** [comment]
Failed. 
What I did is:
1. User A, reset secret address of calendar X => Copy address of calendar X = X1
2. User A, reset secret address of calendar Y => Copy address of calendar Y = Y1
3. User A goes back to calendar X, DON'T reset => Copy address of calendar Xx

Expected result:
Address in step 3 = address in step 1 because user A didn't reset the address

Current behavior: the address is different

**Comment by hantt12** [comment]
Oops sorry I commented on the wrong ticket, the above comment is for https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/536

**Comment by hantt12** [comment]
Still failed as I test today 9th May

**Comment by tlle14** [comment]
Retest pass!
The secret URLs before and after another imported to their calendar are identical.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/80829fcf-c2f3-4ec6-9948-8d95c269dba5)
