### ISSUE TITLE
Error log displays when open "create a new event" modal 

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#52]
**Actual Result**

When opening "create a new event" modal, it generates an error log

![error_log](https://user-images.githubusercontent.com/69950655/90753720-2564ee00-e303-11ea-901e-b4e16cafd15a.gif)

**Expected result**

Please investigate the error log, it shouldn't be shown.

**Steps**

On Firefox

1. Navigate to a calendar module

2. Click on the calendar to create a new event

**Environment**

Test link: https://dev.open-paas.org/
Browser: 
- Ubuntu Firefox 79.0
- Ubuntu Chrome 74.0

**Comment by rezk2ll** [comment]
fixed in https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/166
