### ISSUE TITLE
"No attendee" label appears when adding an attendee in the new event

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#53]
**Actual Result**

When adding a new attendee to the event, "No attendee" label appears

![image](https://user-images.githubusercontent.com/69950655/90847543-eed7b380-e394-11ea-9711-dee688c05c79.png)

![no_attendee](https://user-images.githubusercontent.com/69950655/90847120-f8ace700-e393-11ea-9bd4-fd93e64e84db.gif)

**Expected result**

"No attendee" label shouldn't display when there has an attendee.

**Steps**

1. Create a new event

2. Add an attendee to the event

**Environment**

Chrome on Ubuntu

**Comment by huy-ta** [comment]
## DoD

#### What I have done

I've fixed the issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/59. Now the "No attendees" label will no longer appear when an attendee is added in a new event

#### Environment tested

- Browser: Chrome (Desktop - Ubuntu), Firefox (Desktop - Ubuntu)
- Mode: Dev, Production

@tlle14 You might want to test this on https://dev.open-paas.org/inbox/ after a few hours. Once verified, please close this issue.

**Comment by tlle14** [comment]
Thank Huy,

Retest pass!
![image](https://user-images.githubusercontent.com/69950655/91255659-85d6ae00-e78f-11ea-8a17-86006a1e74f2.png)
