### ISSUE TITLE
Email notification changes show wrong information when creating a recurring event exception

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#534]
When creating a new exception on a recurring event, the notification email show erroneous changes.

#### How to reproduce

- User A creates a recurring event inviting User B
- User B receives a standard notification
- User A modifies one event in the recurring series
- User B should receive the broken notification

#### Current behaviour

The notification email show erroneous changes.

![image.png](https://images.zenhubusercontent.com/5ff41de802ab506ec3e827b9/b55940c3-2728-4183-8fa6-9f0f1bd5918c)

#### Expected behaviour

The notification email should show the correct changes.

DEV NOTE:

When checking differences, if an exception is created, there's no event to compare.
We need to compare with the exception generated by the recurring rule.

**Comment by huy-ta** [comment]
## DoD

#### What I have done

I have resolved the issue via https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/307.

#### Environment tested

Chrome 90.0.4430.93 on Ubuntu 20.04.

**Comment by hantt12** [comment]
Still failed

Invitation email:

![Capture.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a59a02ea-8a29-4042-a6cf-8888fd94627e)

Update email:

![Capture.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/16cd5adc-3ddf-46df-993b-8308d8b7b76e)

**Comment by tlle14** [comment]
Retest pass!

Invitation email
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/05f655b3-8075-4938-ac59-a43947cf4132)

Updated email
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3e6f7950-ffac-456f-a0e8-88d8e5954a48)
