### ISSUE TITLE
ICS secret address gets reset when getting the secret address of another calendar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#536]
#### Steps to reproduce

1. Get the secret address of the default calendar
2. Get the secret address of another calendar
3. Get the secret address of the default calendar again (without pressing the "RESET SECRET ADDRESS" button)

#### Current behaviour

The secret address of the default calendar is reset.

#### Expected behaviour

The secret address of the default calendar should still be the same.

**Comment by hantt12** [comment]
Failed. Tested in QA platform on 7th May

**Comment by tlle14** [comment]
Retest pass!
![Peek 2021-05-18 14-53](https://user-images.githubusercontent.com/69950655/118613974-77cb3080-b7e9-11eb-8176-d6e150098d44.gif)
