### ISSUE TITLE
Recurrence icon doesn't display for repeated events with specified date-time

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#54]
**Actual Result**

Recurrence icon only displays for the repeated all-day event, not for the event with specified date-time 

![recurrence_icon](https://user-images.githubusercontent.com/69950655/90851281-6c53f180-e39e-11ea-848a-26702a300af0.gif)

**Expected result**

The repeated events with specified date-time should have a recurrence icon

**Environment**

Chrome/Firefox on Ubuntu

**Comment by huy-ta** [comment]
## DoD

#### What I have done

I've fixed the issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/62. Now recurrent events with a small duration (less than 45 minutes for desktop and 60 minutes for mobile) will also show the recurrence icons.

#### Environment tested

- Browser: Chrome (Desktop - Ubuntu), Firefox (Desktop - Ubuntu)
- Mode: Dev, Production

@tlle14 You might want to test this on https://dev.open-paas.org/inbox/ after a few hours. Once verified, please close this issue.
