### ISSUE TITLE
Event invitation emails for all-day events are wrong

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#541]
#### Steps to reproduce

- As User A:

1. Login and go to Calendar
2. Create an all-day event and invites User B

- As User B:

1. Login and go to Inbox
2. Check the event invitation email that has just arrived

#### Current behaviour

The date in the email body is one day earlier than the actual date of the event.

#### Expected behaviour

The date in the email body should be the same as the actual date of the event.

**Comment by huy-ta** [comment]
@rezk2ll Can you reproduce this bug?

**Comment by rezk2ll** [comment]
no

**Comment by huy-ta** [comment]
I also can no longer reproduce this anywhere, including the production environment (oplngcom).
