### ISSUE TITLE
Translation issue in calendar

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#57]
- [x]  **Event details -All languages**
![image](https://user-images.githubusercontent.com/69950655/90869205-1a24c780-e3c2-11ea-9084-9ba0a892e62f.png)
![image](https://user-images.githubusercontent.com/69950655/91022623-ab44aa00-e61f-11ea-9596-b255f3b0a84e.png)

Actual: Date picker displays days in a week in English
Expected: Should display in the corresponding languages

- [x] **Adding a shared caledar - all languages**

![add_calendar](https://user-images.githubusercontent.com/69950655/91040047-cb806300-e637-11ea-9b63-349e4dfc7551.gif)

Actual: When adding a shared calendar, it displays a message in English: "Successfully added shared calendar"
Expected: The message should be translated into the corresponding language.

- [x] **Configuration saved message when saving calendar setting - FR**
![Peek 2020-08-21 16-29](https://user-images.githubusercontent.com/69950655/90875793-e189eb80-e3cb-11ea-80ef-7c2a5894e51e.gif)

Actual: Display "Configuration saved"
Expected: Please translate to French

- [x] **Calendar setting > Display - all languages**
![image](https://user-images.githubusercontent.com/69950655/91037869-f4065e00-e633-11ea-84e2-27e62e6057fa.png)

Actual: "Show" option is in English
Expected: It should be translated to the corresponding language

- [x] **Event  invitation mail/Updating mail/ Cancelation mail - FR**
![image](https://user-images.githubusercontent.com/69950655/90877044-a688b780-e3cd-11ea-9598-a85eca642193.png)
![image](https://user-images.githubusercontent.com/69950655/91000594-b386f000-e5f3-11ea-88f1-a9b51e7d1375.png)

Actual: Some places in English have been marked in red
Expected: Please translate to French

- [x] **Tooltip is in English-FR** 
![tooltip](https://user-images.githubusercontent.com/69950655/91001301-905d4000-e5f5-11ea-8573-7b55c074490d.gif)

Actual: Tooltip "Mail to attendees" is in English
Expected: It should be translated to French

- [x] **Response message in the invitation mail - FR**
![translation](https://user-images.githubusercontent.com/69950655/90878482-c8833980-e3cf-11ea-8313-e3e2662ae753.gif)

Actual: After the response to an invitation email, it displays a message in English.
Expected: Messages should be French

- [x] **Incorrect word - EN**
![image](https://user-images.githubusercontent.com/69950655/90880858-5dd3fd00-e3d3-11ea-8d5c-4fff36330cf9.png)

Actual: In the invitation email, there're some places display "a videoconference" - which is not a word
Expected: It should be "a video conference"

- [x] **Event details > Recurrence - Chinese**
![image](https://user-images.githubusercontent.com/69950655/91024507-3de64880-e622-11ea-9269-ab55093f23aa.png)

Actual: In the event details, the recurrence option displays days in a week and label "on" in english
Expected: It should be translated into Chinese

- [x] **The note for video conference in event details modal - Chinese**
![image](https://user-images.githubusercontent.com/69950655/91031638-15168100-e62b-11ea-96f1-0914deb4a320.png)

Actual: Open the event details, the note for video conference is in English
Expected: It should be translated into Chinese

**Comment by asmaNode** [comment]
This issue will be splitted on a separate PRs

**Comment by asmaNode** [comment]
Adding a shared caledar - all languages : #336
