### ISSUE TITLE
Declined event displays in planing section

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#60]
**Actual Result**

The User declined the event but it still appears in his planing section

![image](https://user-images.githubusercontent.com/69950655/91005096-2a29ea80-e600-11ea-8e62-328dd7082e43.png)

**Expected result**

The declined event shouldn't be in planing section

**Environment**

Browser on Ubuntu

**Comment by pbson** [comment]
## Definition of Done

#### What I have done

I have resolved this issue via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/164.
1. When user decide to show declined event via manage calendars. On planning section, that event have style depends on the participation status of the calendar owner. Here's the result:

![Peek 2020-10-06 13-41](https://user-images.githubusercontent.com/32195667/95167531-0ac6d580-07da-11eb-9fd6-1c93ff1ab435.gif)

2. When user decide to hide declined event via manage calendars. On planning section, declined event is hidden.

#### Environments tested

- Browser: Chrome & Firefox Desktop (Ubuntu)
- Mode: Dev (on the local computer)
