### ISSUE TITLE
Mobile > The date/time picker on android is not convenient to use

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#63]
**Actual Result**

On Android, it uses date/time picker as on the PC, which makes it's not convenient to use.

![processed1](https://user-images.githubusercontent.com/69950655/91021667-43da2a80-e61e-11ea-9e4a-47aa25000679.jpeg)
![processed](https://user-images.githubusercontent.com/69950655/91021684-49d00b80-e61e-11ea-9d7d-57be2ba6628b.jpeg)

While on iOS, it uses the default time picker of IOS which is fit the mobile screen.

**Expected result**

Mobile Android should use the default date/time picker of Android.

**Environment**

Chrome on mobile Android 8.1.0
Phone: Redmi Go

**Comment by MichaelBailly** [comment]
I guess that one can be closed

**Comment by tlle14** [comment]
I agree.
