### ISSUE TITLE
Error log appears when save the event respond

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#68]
**Actual Result**

On the desktop event, respond then click "Save" button, it's able to save but generates error logs:

![save_the response](https://user-images.githubusercontent.com/69950655/91253453-085c6f00-e78a-11ea-811e-471e5ceb2370.gif)

**Expected result**

Please investigate the error log. It shouldn't appear

**Environment**

Desktop Ubuntu

Single event

**Comment by rezk2ll** [comment]
fixed in https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/166
