### ISSUE TITLE
Mobile > iOS > The next/previous button on the header of planning sidebar

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#69]
**Actual Result**

On the planning sidebar, It's hard to tap on the next/ previous buttons to change the date.

![3E669B02-0FE8-4F7A-AD8D-D2BE1157B8A0](https://user-images.githubusercontent.com/69950655/91274450-e7574680-e7a8-11ea-815d-e90308701370.jpg)

**Expected result**

Please investigate the issue. 
It might because of the tooltips. Tooltips are no more needed for mobile/tablet devices, so please remove them.

**Environment**

Chrome on iOS Mobile/Tablet

**Comment by huy-ta** [comment]
I cannot reproduce this issue.
