### ISSUE TITLE
Mobile/Tablet > Modules menu is displaying incorrect

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#70]
**Actual Result**

1. On mobile, both ios and android, "Video conference" label sticks to the menu border

![mobile](https://user-images.githubusercontent.com/69950655/91281681-977d7d00-e7b2-11ea-91b3-4a786223b9e0.jpg)

2. On Tablet - ipad, the menu has been cut by the sidebar

![tablet](https://user-images.githubusercontent.com/69950655/91282178-33a78400-e7b3-11ea-969d-278930e0c33a.jpeg)
 
**Expected result**

The modules menu should display normally 

**Environment**
- Android/Ios Mobile
- Tablet - iPad Air 2

**Comment by huy-ta** [comment]
## DoD

#### What I have done

I have fixed the issue where the application grid is truncated on iOS devices. Now the application grid is no longer truncated.

#### Environment tested

- Device: iPhone 7 (iOS 13.3.1)
- Browser: Mobile Safari 13

**Comment by tlle14** [comment]
Hi @huy-ta 

Retest failed!
When pulling the page to refresh, the menu is broken again. 

And I expect the menu displaying overlay the sidebar, not be cut by the sidebar 
![IMG_0182](https://user-images.githubusercontent.com/69950655/93730210-d657f480-fbf1-11ea-9ddd-25e8fdce46c8.PNG)

**Comment by huy-ta** [comment]
@tlle14 Does it always fail or does it fail randomly?

**Comment by tlle14** [comment]
> @tlle14 Does it always fail or does it fail randomly?

It always fails:D

**Comment by hantt12** [comment]
Fails on Iphone 7, iphone X

Passes on iphone 11, ipad Air 2

**Comment by tlle14** [comment]
Hi @huy-ta 

I've investigated and found that the issue happens when the menu sidebar has a scroll bar.
 Please help us fix this issue. 

Thanks!
