### ISSUE TITLE
I cannot select "My Agenda" when importing an ICS

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-calendar#85]
Reproduction steps:

* set "My Agenda" -> "Settings" -> "Public rights" to "See all events details"
* click on "+" => "Import"
* use the dropdown to choose the target calendar

**Current behaviour**

My Agenda is not in the list

![image](https://user-images.githubusercontent.com/1465817/92403853-a5c48500-f132-11ea-8924-45ffeadaa110.png)

**Expected behaviour**

My Agenda is in the list

**Analyses**

The rules to set whether the calendar is writable is wrong https://github.com/OpenPaaS-Suite/esn-frontend-calendar/blob/main/src/esn.calendar.libs/app/services/cal-ui-authorization-service.js#L47 :

```javascript
return !!calendar && calendar.isOwner(userId) && !calendar.isSubscription() && !calendar.isPublic();
```

calendar.isPublic() here should means "has been shared with me using public sharing" and not "is publicely shared or not".

**Comment by tuanlc** [comment]
### Definition of Done
- Done: The bug was fixed.
- Tested: On local with production mode
- Impact: Import calendar from ICS file feature

**Comment by tlle14** [comment]
Thank @tuanlc 

Retest pass!

![image](https://user-images.githubusercontent.com/69950655/92468608-a24a0000-f1fd-11ea-9903-c6d188b88730.png)
