### ISSUE TITLE
Alarm email is broken

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-calendar#95]
The "description" icon is missing

![Capture d’écran 2020-09-10 à 10 38 27](https://user-images.githubusercontent.com/264403/92702810-ea7a3700-f351-11ea-9282-b142e44da4e3.png)

**Comment by billyfrost418** [comment]
@chamerling I have tried to reproduce this bug on https://openpaas.linagora.com. However, there is no missing icon. Could you please check it again and confirm the issue?
Below is the email I received
![Screenshot from 2020-09-15 16-10-09](https://user-images.githubusercontent.com/26143938/93190889-17718400-f76e-11ea-88c8-e58da17d902b.png)

**Comment by chamerling** [comment]
@billyfrost418 in my event, I added a description and the missing icon is the description one

**Comment by tuanlc** [comment]
### Definition Of Done
- Done: 
  - The description icon is brought back
  - Backport the fix to release-1.8.x
- Impact: No
- Testing:
  - The fix was deployed on DEV platform
  - On production: needs to release and deploy to production cc @MichaelBailly

**Comment by tlle14** [comment]
Thank @tuanlc 

Retest pass on DEV platform
![image](https://user-images.githubusercontent.com/69950655/93744026-4d55b300-fc1b-11ea-9ffa-814a7ca7c360.png)
