### ISSUE TITLE
Links to calendar are wrong in email

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-calendar#96]
Since we changed the deployment URLs, links in emails are https://host/#/calendar/ which do not route to anything but open inbox which is the default route.

![Capture d’écran 2020-09-10 à 10 43 12](https://user-images.githubusercontent.com/264403/92703425-74c29b00-f352-11ea-9194-168a758232f3.png)

**Expected result**

Open the calendar SPA which is located in https://host/calendar/#/calendar

**Comment by rezk2ll** [comment]
related merge request: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/669
